const ksThirdSemComputer = [
  {
    id: "computer-third-engineeringmathiii",
    title: "Engineering Mathematics III",
    objective:
      "To round out the students’ preparation for more sophisticated applications with an introduction to linear algebra, Fourier Series, Laplace Transforms, integral transformation theorems and linear programming.",
    chapters: [
      {
        title: "Determinants and Matrices(11 hours)",
        topics: [
          "Determinant and its properties",
          "Solution of system of linear equations",
          "Algebra of matrices",
          "Complex matrices",
          "Rank of matrices",
          "System of linear equations",
          "Vector spaces",
          "Linear transformations",
          "Eigen value and Eigen vectors",
          "The Cayley-Hamilton theorem and its uses",
          "Diagonalization of matrices and its applications",
        ],
      },
      {
        title: "Line, Surface and Volume Integrals(12 hours)",
        topics: [
          "Line integrals",
          "Evaluation of line integrals",
          "Line integrals independent of path",
          "Surfaces and surface integrals",
          "Green’s theorem in the Plane and its applications",
          "Stoke’s theorem (without proof) and its applications",
          "Volume integrals; Divergence theorem of Gauss (without proof) and its applications",
        ],
      },
      {
        title: "Laplace Transform(8 hours)",
        topics: [
          "Definitions and properties of Laplace Transform",
          "Derivations of basic formulae of Laplace Transform",
          "Inverse Laplace Transform: Definition and standard formulae of inverse Laplace Transform",
          "Theorems on Laplace transform and its inverse",
          "Convolution and related problems",
          "Applications of Laplace Transform to ordinary differential equations",
        ],
      },
      {
        title: "Fourier Series(5 hours)",
        topics: [
          "Fourier Series",
          "Periodic functions",
          "Odd and even functions",
          "Fourier series for arbitrary range",
          "Half range Fourier series",
        ],
      },
      {
        title: "Linear Programming(9 hours)",
        topics: [
          "System of Linear Inequalities in two variables",
          "Linear Programming in two dimensions: A Geometrical Approach",
          "A Geometric introduction to the Simplex method",
          "The Simplex method: Maximization with Problem constraints of the form “≤”",
          "The Dual: Maximization with Problem Constraints of the form “≥”",
          "Maximization and Minimization with mixed Constraints. The two-phase method(An alternative to the Big M Method)",
        ],
      },
    ],
    practicals: [],
    references: [
      'E. Kreszig, "Advance Engineering Mathematics", Willey, New York.',
      'M.M Gutterman and Z.N.Nitecki, "Differential Equation, a First Course", 2nd Edition, saunders, New York.',
    ],
    evaluationScheme:
      '<table border="1" cellspacing="0" cellpadding="0"> <tbody> <tr> <td width="72" valign="top"> <p align="center"><b>Chapters</b></p> </td> <td width="66" valign="top"> <p align="center"><b>Hours</b></p> </td> <td width="138" valign="top"> <p align="center"><b>Marks distribution*</b></p> </td> </tr> <tr> <td width="72" valign="top"> <p align="center">1</p> </td> <td width="66" valign="top"> <p align="center">11</p> </td> <td width="138" valign="top"> <p align="center">20</p> </td> </tr> <tr> <td width="72" valign="top"> <p align="center">2</p> </td> <td width="66" valign="top"> <p align="center">12</p> </td> <td width="138" valign="top"> <p align="center">20</p> </td> </tr> <tr> <td width="72" valign="top"> <p align="center">3</p> </td> <td width="66" valign="top"> <p align="center">8</p> </td> <td width="138" valign="top"> <p align="center">15</p> </td> </tr> <tr> <td width="72" valign="top"> <p align="center">4</p> </td> <td width="66" valign="top"> <p align="center">5</p> </td> <td width="138" valign="top"> <p align="center">10</p> </td> </tr> <tr> <td width="72" valign="top"> <p align="center">5</p> </td> <td width="66" valign="top"> <p align="center">9</p> </td> <td width="138" valign="top"> <p align="center">15</p> </td> </tr> <tr> <td width="72" valign="top"> <p align="center">Total</p> </td> <td width="66" valign="top"> <p align="center">45</p> </td> <td width="138" valign="top"> <p align="center">80</p> </td> </tr> </tbody> </table>',
  },
  {
    id: "computer-third-objectorientedprogramming",
    title: "Object Oriented Programming",
    objective:
      "To familiarize students with the C++ programming language and use the language to develop pure object oriented programs.",
    chapters: [
      {
        title: "Introduction to Object Oriented Programming(3 hours)",
        topics: [
          "Issues with Procedure Oriented Programming",
          "Basic of Object Oriented Programming (OOP)",
          "Procedure Oriented versus Object Oriented Programming",
          "Concept of Object Oriented Programming:- Object,Class,Abstraction,Encapsulation,Inheritance,Polymorphism,",
          "Example of Some Object Oriented Languages",
          "Advantages and Disadvantages of OOP",
        ],
      },
      {
        title: "Introduction to C++(2 hours)",
        topics: [
          "The Need of C++",
          "Features of C++",
          "C++ Versus C",
          "History of C++",
        ],
      },
      {
        title: "C++ Language Constructs(6 hours)",
        topics: [
          "C++ Program Structure",
          "Character Set and Tokens:- Keywords,Identifiers,Literals,Operators and Punctuators,",
          "Variable Declaration and Expression",
          "Statements",
          "Data Type",
          "Type Conversion and Promotion Rules",
          "Preprocessor Directives",
          "Namespace",
          "User Defined Constant",
          "Input/Output Streams and Manipulators",
          "Dynamic Memory Allocation with new and delete",
          "Condition and Looping",
          "Functions:- Function Syntax,Function Overloading,Inline Functions,Default Argument,Pass by Reference,Return by Reference,",
          "Array, Pointer and String",
          "Structure, Union and Enumeration",
        ],
      },
      {
        title: "Objects and Classes(6 hours)",
        topics: [
          "C++ Classes",
          "Access Specifiers",
          "Objects and the Member Access",
          "Defining Member Function",
          "Constructor:- Default Constructor,Parameterized Constructor,Copy Constructor,",
          "Destructors",
          "Object as Function Arguments and Return Type",
          "Array of Objects",
          "Pointer to Objects and Member Access",
          "Dynamic Memory Allocation for Objects and Object Array",
          "Pointer",
          "Static Data Member and Static Function",
          "Constant Member Functions and Constant Objects",
          "Friend Function and Friend Classes",
        ],
      },
      {
        title: "Operator Overloading(5 hours)",
        topics: [
          "Overloadable Operators",
          "Syntax of Operator Overloading",
          "Rules of Operator Overloading",
          "Unary Operator Overloading",
          "Binary Operator Overloading",
          "Operator Overloading with Member and Non Member Functions",
          "Data Conversion: Basic–User Defined and User Defined–User Defined",
          "Explicit Constructors",
        ],
      },
      {
        title: "Inheritance(5 hours)",
        topics: [
          "Base and Derived Class",
          "protected Access Specifier",
          "Derived Class Declaration",
          "Member Function Overriding",
          "Forms of Inheritance: Single, Multiple, Multilevel, Hierarchical, Hybrid, Multipath",
          "Multipath Inheritance and Virtual Base Class",
          "Constructor Invocation in Single and Multiple Inheritances",
          "Destructor in Single and Multiple Inheritances",
        ],
      },
      {
        title: "Polymorphism and Dynamic Binding(4 hours)",
        topics: [
          "Need of Virtual Function",
          "Pointer to Derived Class",
          "Definition of Virtual Functions",
          "Array of Pointers to Base Class",
          "Pure Virtual functions and Abstract Class",
          "Virtual Destructor",
          "Reinterpret_cast Operator",
          "Run-Time Type Information:- Dynamic_cast Operator,Type_id Operator,",
        ],
      },
      {
        title: "Stream Computation for Console and File Input/Output(5 hours)",
        topics: [
          "Stream Class Hierarchy for Console Input/Output",
          "Testing Stream Errors",
          "Unformatted Input/Output",
          "Formatted Input/Output with IOS Member functions and Flags",
          "Formatting with Manipulators",
          "Stream Operator Overloading",
          "File Input/output with Streams",
          "File Stream Class Hierarchy",
          "Opening and Closing files",
          "Read/Write from File",
          "File Access Pointers and their Manipulators",
          "Sequential and Random Access to File",
          "Testing Errors during File Operations",
        ],
      },
      {
        title: "Templates(5 hours)",
        topics: [
          "Function Template",
          "Overloading Function Template:- Overloading with Functions,Overloading with other Template,",
          "Class Template:- Function Definition of Class Template,Non-Template Type Arguments,Default Arguments with Class Template,",
          "Derived Class Template",
          "Introduction to Standard Template Library:- Containers,Algorithms,Iterators,",
        ],
      },
      {
        title: "Exception Handling(4 hours)",
        topics: [
          "Error Handling",
          "Exception Handling Constructs (try, catch, throw)",
          "Advantage over Conventional Error Handling",
          "Multiple Exception Handling",
          "Rethrowing Exception",
          "Catching All Exceptions",
          "Exception with Arguments",
          "Exceptions Specification for Function",
          "Handling Uncaught and Unexpected Exceptions",
        ],
      },
    ],
    practicals: [
      "There will be about 12 lab exercises covering the course. At the end of the course students must complete a programming project on object oriented programming with C++.",
    ],
    references: [
      "Robert Lafore, “Object Oriented Programming in C++”, 4th Edition 2002, Sams Publication",
      "Daya Sagar Baral and Diwakar Baral, “The Secrets of Object Oriented Programming in C++”, 1st Edition 2010, Bhundipuran Prakasan",
      "Harvey M. Deitel and Paul J. Deitel, “C++ How to Program”, 3rd Edition 2001, Pearson Education Inc.",
      "D. S. Malik, “C++ Programming”, 3rd Edition 2007, Thomson Course Technology",
      "Herbert Schildt, “C++: The Complete Reference”, 4th Edition 2003, Tata McGraw Hill",
    ],
    evaluationScheme:
      '<table border="1" cellspacing="0" cellpadding="0"> <tbody> <tr> <td width="90" valign="top"> <p align="center"><b>Chapters</b></p> </td> <td width="84" valign="top"> <p align="center"><b>Hours</b></p> </td> <td width="162" valign="top"> <p align="center"><b>Marks distribution*</b></p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">1,2,4</p> </td> <td width="84" valign="top"> <p align="center">11</p> </td> <td width="162" valign="top"> <p align="center">20</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">3</p> </td> <td width="84" valign="top"> <p align="center">6</p> </td> <td width="162" valign="top"> <p align="center">10</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">5</p> </td> <td width="84" valign="top"> <p align="center">5</p> </td> <td width="162" valign="top"> <p align="center">10</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">6</p> </td> <td width="84" valign="top"> <p align="center">5</p> </td> <td width="162" valign="top"> <p align="center">10</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">8</p> </td> <td width="84" valign="top"> <p align="center">5</p> </td> <td width="162" valign="top"> <p align="center">10</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">7,9,10</p> </td> <td width="84" valign="top"> <p align="center">13</p> </td> <td width="162" valign="top"> <p align="center">20</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">Total</p> </td> <td width="84" valign="top"> <p align="center">45</p> </td> <td width="162" valign="top"> <p align="center">80</p> </td> </tr> </tbody> </table>',
  },
  {
    id: "computer-third-electriccircuittheory",
    title: "Electric Circuit Theory",
    title: "Electric Circuit Theory",
    objective:
      "sTo continue work in Basic Electrical Engineering including the use of the Laplace Transform to determine the time and frequency domain responses of electric circuits.",
    chapters: [
      {
        title: "Network Analysis of AC circuit & Dependent Sources(8 hours)",
        topics: [
          "Mesh Analysis",
          "Nodal Analysis",
          "Series & parallel resonance in RLC circuits:- Impedance and phase angle of series Resonant Circuit,Voltage and current in series resonant circuit,Band width of the RLC circuit.,High-Q and Low-Q circuits,",
        ],
      },
      {
        title: "Initial Conditions(2 hours)",
        topics: [
          "Characteristics of various network elements",
          "Initial value of Derivatives",
          "Procedure for evaluating initial conditions",
          "Initial condition in the case of RLC network",
        ],
      },
      {
        title: "Transient analysis in RLC circuit by direct solution(10 hours)",
        topics: [
          "Introduction",
          "First order Differential equation",
          "Higher order homogeneous and non-homogeneous differential equations",
          "Particular integral by method of undetermined coefficients",
          "Response of R-L circuit with:- DC excitation,Exponential excitation,Sinusoidal excitation,",
          "Response of R-C circuit with:- DC excitation,Exponential excitation,Sinusoidal excitation,",
          "Response of series RLC circuit with:- DC excitation,Exponential excitation,Sinusoidal excitation,",
          "Response of parallel RLC circuit with DC excitation",
        ],
      },
      {
        title:
          "Transient analysis in RLC circuit by Laplace Transform(8 hours)",
        topics: [
          "Introduction",
          "The Laplace Transformation",
          "Important properties of Laplace transformation",
          "Use of Partial Fraction expansion in analysis using Laplace Transformations",
          "Heaviside's partial fraction expansion theorem",
          "Response RL circuit with:- DC excitation,Exponential excitation,Sinusoidal excitation,",
          "Response of RC circuit with:- DC excitation,Exponential excitation,Sinusoidal excitation,",
          "Response of series RLC circuit with:- DC excitation,Exponential excitation,Sinusoidal excitation,",
          "Response of parallel RLC circuit with exponential excitation",
          "Transfer functions Poles and Zeros of Networks",
        ],
      },
      {
        title: "Frequency Response of Network(6 hours)",
        topics: [
          "Introduction",
          "Magnitude and Phase response",
          "Bode Diagrams",
          "Bandwidth of Series & parallel Resonance circuits",
          "Basic concept of filters, high pass, low pass, band pass and band stop filters",
        ],
      },
      {
        title: "Fourier Series and transform(5 hours)",
        topics: [
          "Basic concept of Fourier series and analysis",
          "Evaluation of Fourier coefficients for periodic non-sinusoidal waveforms in electric networks",
          "Introduction of Fourier transforms",
        ],
      },
      {
        title: "Two-port Parameter of Networks(6 hours)",
        topics: [
          "Definition of two-port networks",
          "Short Circuit admittance parameters",
          "Open Circuits impedance parameters",
          "Transmission Short Circuit admittance parameters",
          "Hybrid Parameters",
          "Relationship and Transformations between sets of parameters",
          "Application to Filters",
          "Applications to Transmission Lines",
          "Interconnection of two-port network(Cascade, series, parallel)",
        ],
      },
    ],
    practicals: [
      "Resonance in RLC series circuit: measurement of resonant frequency",
      "Transient Response in first Order System passive circuits:\ni) measure step and impulse response of RL and RC circuit using oscilloscope\nii) relate time response to analytical transfer functions calculations",
      "Transient Response in Second Order System passive circuits:\ni) measure  step and impulse response of RLC series and parallel circuits using oscilloscope\nii)relate time response to transfer functions and pole-zero configuration",
      "Frequency Response of first  order passive circuits:\ni) measure amplitude and phase response and plot bode diagrams for RL, RC and RLC circuits\nii) relate Bode diagrams to transfer functions and pole zero configuration circuit",
      "Frequency Response of second order passive circuits:\ni) measure amplitude and phase response and plot bode diagrams for RL, RC and RLC circuits\nii) relate Bode diagrams to transfer functions and pole zero configuration circuit",
    ],
    references: [
      'M. E. Van Valkenburg, "Network Analysis", third edition Prentice Hall, 2010.',
      'William H. Hyat. Jr. & Jack E. Kemmerly, "Engineering Circuits Analysis", Fourth edition, McGraw Hill International Editions, Electrical Engineering Series, 1987.',
      'Michel D. Cilletti, "Introduction to Circuit Analysis and Design", Holt, Hot Rinehart and Winston International Edition, New York, 1988.',
    ],
    evaluationScheme:
      '<table border="1" cellspacing="0" cellpadding="0"> <tbody> <tr> <td width="84" valign="top"> <p align="center"><b>Chapters</b></p> </td> <td width="96" valign="top"> <p align="center"><b>Hours</b></p> </td> <td width="143" valign="top"> <p align="center"><b>Marks Distribution*</b></p> </td> </tr> <tr> <td width="84"> <p align="center">1</p> </td> <td width="96"> <p align="center">8</p> </td> <td width="143"> <p align="center">12</p> </td> </tr> <tr> <td width="84"> <p align="center">2</p> </td> <td width="96"> <p align="center">2</p> </td> <td width="143"> <p align="center">6</p> </td> </tr> <tr> <td width="84"> <p align="center">3</p> </td> <td width="96"> <p align="center">10</p> </td> <td width="143"> <p align="center">16</p> </td> </tr> <tr> <td width="84"> <p align="center">4</p> </td> <td width="96"> <p align="center">8</p> </td> <td width="143"> <p align="center">12</p> </td> </tr> <tr> <td width="84"> <p align="center">5</p> </td> <td width="96"> <p align="center">6</p> </td> <td width="143"> <p align="center">12</p> </td> </tr> <tr> <td width="84"> <p align="center">6</p> </td> <td width="96"> <p align="center">5</p> </td> <td width="143"> <p align="center">10</p> </td> </tr> <tr> <td width="84"> <p align="center">7</p> </td> <td width="96"> <p align="center">6</p> </td> <td width="143"> <p align="center">12</p> </td> </tr> <tr> <td width="84"> <p align="center">Total</p> </td> <td width="96"> <p align="center">45</p> </td> <td width="143"> <p align="center">80</p> </td> </tr> </tbody> </table>',
  },
  {
    id: "computer-third-theoryofcomputation",
    title: "Theory of Computation",
    objective:
      "To provide basic understanding of theory of automata, formal languages, turing machines and computational complexity.",
    chapters: [
      {
        title: "Introduction (4 hours)",
        topics: [
          "Set, relation, function, Proof techniques.",
          "Alphabets, language, regular expression.",
        ],
      },
      {
        title: "Finite Automata  (12 hours)",
        topics: [
          "Deterministic Finite Automata.",
          "Non-Deterministic Finite Automata.",
          "Equivalence of regular language and finite automata.",
          "Regular language, properties of regular language.",
          "Pumping lemma for regular language.",
          "Decision algorithms for regular languages.",
        ],
      },
      {
        title: "Context free language (12 hours)",
        topics: [
          "Context free grammar.",
          "Derivative trees, simplification of context free grammar.",
          "Chomsky normal form.",
          "Push down automata.",
          "Equivalence of context free language and push down automata.",
          "Pumping lemma for context free language.",
          "Properties of context free language.",
          "Decision algorithms for context free language.",
        ],
      },
      {
        title: "Turing machine  (10 hours)",
        topics: [
          "Definition of Turing machine, notation for Turing machine.",
          "Computing with Turing machine.",
          "Extensions of Turing machine.",
          "Unrestricted grammar.",
          "Recursive function theory.",
        ],
      },
      {
        title: "Undecidability  (5 hours)",
        topics: [
          "The Church-Turing thesis.",
          "Halting Problem, Universal Turing machine.",
          "Undecidable problems about Turing machines, grammars.",
          "Properties of Recursive, Recursively enumerable languages.",
        ],
      },
      {
        title: "Computational Complexity  (2 hours)",
        topics: ["Class P, Class NP, NP-complete problems."],
      },
    ],
    practicals: [],
    references: [
      "H. R. Lewis, C. H. Papadimitriou, “Elements of theory of computation”, Pearson Education.",
      "Michael Sipser, “Introduction to the Theory of Computation”, Thomson Course Technology.",
    ],
    evaluationScheme:
      '<table border="1" cellspacing="0" cellpadding="0"> <tbody> <tr> <td width="90" valign="top"> <b>Chapters</b> </td> <td width="90" valign="top"> <p align="center"><b>Hours</b></p> </td> <td width="144" valign="top"> <p align="center"><b>Marks Distribution*</b></p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">1</p> </td> <td width="90" valign="top"> <p align="center">4</p> </td> <td width="144" valign="top"> <p align="center">7</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">2</p> </td> <td width="90" valign="top"> <p align="center">12</p> </td> <td width="144" valign="top"> <p align="center">21</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">3</p> </td> <td width="90" valign="top"> <p align="center">12</p> </td> <td width="144" valign="top"> <p align="center">21</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">4</p> </td> <td width="90" valign="top"> <p align="center">10</p> </td> <td width="144" valign="top"> <p align="center">17</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">5</p> </td> <td width="90" valign="top"> <p align="center">5</p> </td> <td width="144" valign="top"> <p align="center">9</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">6</p> </td> <td width="90" valign="top"> <p align="center">2</p> </td> <td width="144" valign="top"> <p align="center">5</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center"><b>Total</b></p> </td> <td width="90" valign="top"> <p align="center"><b>45</b></p> </td> <td width="144" valign="top"> <p align="center"><b>80</b></p> </td> </tr> </tbody> </table>',
  },
  {
    id: "computer-third-electromagnetics",
    title: "Electromagnetics",
    objective:
      "To provide basic understanding of the fundamentals of Electromagnetics.",
    chapters: [
      {
        title: "Introduction(3 hours)",
        topics: [
          "Co-ordinate system",
          "Scalar and vector fields",
          "Operations on scalar and vector fields",
        ],
      },
      {
        title: "Electric field(11 hours)",
        topics: [
          "Coulomb’s law",
          "Electric field intensity",
          "Electric flux density",
          "Gauss’s law and applications",
          "Physical significance of divergence; Divergence theorem.",
          "Electric potential, Potential gradient",
          "Energy density in electrostatic field",
          "Electric properties of material medium",
          "Free and bound Charges, Polarization, Relative permittivity, Electric dipole",
          "Electric Boundary conditions",
          "Current, Current density, Conservation of charge, Continuity equation, Relaxation time",
          "Boundary value problems, Laplace and Poisson equations and their solutions, Uniqueness theorem.",
          "Graphical field plotting, Numerical integration.",
        ],
      },
      {
        title: "Magnetic field(9 hours)",
        topics: [
          "Biot-Savart’s law",
          "Magnetic field intensity",
          "Ampere’s circuital law and its application",
          "Magnetic flux density",
          "Physical significance of curl, Stoke’s theorem",
          "Scalar and Magnetic vector potential",
          "Magnetic properties of material medium",
          "Magnetic force, Magnetic torque, Magnetic moment, Magnetic dipole, Magnetization",
          "Magnetic boundary condition",
        ],
      },
      {
        title: "Wave equation and Wave propagation(12 hours)",
        topics: [
          "Faraday’s law, Transformer emf, Motional emf",
          "Displacement current",
          "Maxwell’s equations in integral and point forms",
          "Wave propagation in lossless and lossy dielectric",
          "Plane waves in free space, lossless dielectric, good conductor",
          "Power and pointing vector",
          "Reflection of plane wave at normal and oblique incidence",
        ],
      },
      {
        title: "Transmission lines(5 hours)",
        topics: [
          "Transmission line equations",
          "Input impedance, Reflection coefficient, Standing wave ratio",
          "Impedance matching, Quarter wave transformer, Single stub matching, Double stub matching",
        ],
      },
      {
        title: "Wave guides(4 hours)",
        topics: [
          "Rectangular wave guide",
          "Transverse electric mode, transverse magnetic mode",
        ],
      },
      {
        title: "Antennas(1 hour)",
        topics: ["Introduction to antenna, antenna types and properties"],
      },
    ],
    practicals: [
      "Teledeltos (electro-conductive)  paper mapping of electrostatic fields.",
      "Determination of dielectric constant, display of a magnetic Hysteresis loop",
      "Studies of wave propagation on a lumped parameter transmission line",
      "Microwave sources, detectors, transmission lines",
      "Standing wave patterns on transmission lines, reflections, power patterns on transmission lines, reflections, power measurement.",
      "Magnetic field measurements in a static magnetic circuit, inductance, leakage flux.",
    ],
    references: [
      "W. H. Hayt, “Engineering Electromagnetics”, McGraw-Hill Book Company.",
      "J. D. Kraus, “Electromagnetics”, McGraw-Hill Book Company.",
      "N. N. Rao, “Elements of Engineering Electromagnetics”, Prentice Hall.",
      "Devid K. Cheng, “Field and Wave Electromagnetics”, Addison-Wesley.",
      "M. N. O. Sadiku, “Elements of Electromagnetics”, Oxford University Press.",
    ],
    evaluationScheme:
      '<table border="1" cellspacing="0" cellpadding="0"> <tbody> <tr> <td width="96" valign="top"> <p align="center"><b>Chapters</b></p> </td> <td width="90" valign="top"> <p align="center"><b>Hours</b></p> </td> <td width="144" valign="top"> <p align="center"><b>Marks distribution*</b></p> </td> </tr> <tr> <td width="96" valign="top"> <p align="center">1</p> </td> <td width="90" valign="top"> <p align="center">3</p> </td> <td width="144" valign="top"> <p align="center">5</p> </td> </tr> <tr> <td width="96" valign="top"> <p align="center">2</p> </td> <td width="90" valign="top"> <p align="center">11</p> </td> <td width="144" valign="top"> <p align="center">20</p> </td> </tr> <tr> <td width="96" valign="top"> <p align="center">3</p> </td> <td width="90" valign="top"> <p align="center">9</p> </td> <td width="144" valign="top"> <p align="center">16</p> </td> </tr> <tr> <td width="96" valign="top"> <p align="center">4</p> </td> <td width="90" valign="top"> <p align="center">12</p> </td> <td width="144" valign="top"> <p align="center">21</p> </td> </tr> <tr> <td width="96" valign="top"> <p align="center">5, 6, 7</p> </td> <td width="90" valign="top"> <p align="center">10</p> </td> <td width="144" valign="top"> <p align="center">16</p> </td> </tr> <tr> <td width="96" valign="top"> <p align="center">Total</p> </td> <td width="90" valign="top"> <p align="center">45</p> </td> <td width="144" valign="top"> <p align="center">80</p> </td> </tr> </tbody> </table>',
  },
  {
    id: "computer-third-digitallogic",
    title: "Digital Logic",
    objective:
      "To introduce basic principles of digital logic design, its implementation and applications.",
    chapters: [
      {
        title: "Introduction (3 hours)",
        topics: [
          "Definitions for Digital Signals",
          "Digital Waveforms",
          "Digital Logic",
          "Moving and Storing Digital Information",
          "Digital Operations",
          "Digital Computer",
          "Digital Integrated Circuits",
          "Digital IC Signal Levels",
          "Clock wave form",
          "Coding:- ASCII Code,BCD,The Excess – 3 Code,The Gray Code,",
        ],
      },
      {
        title: "Digital Logic(1 hour)",
        topics: [
          "The Basic Gates: NOT, OR, AND",
          "Universal Logic Gates: NOR, NAND",
          "AND-OR-INVERT Gates",
          "Positive and Negative Logic",
          "Introduction to HDL",
        ],
      },
      {
        title: "Combinational Logic Circuits(5 hours)",
        topics: [
          "Boolean Laws and Theorems",
          "Sum-of-Products Method",
          "Truth Table to Karnaugh Map",
          "Pairs, Quads, and Octets",
          "Karnaugh Simplifications",
          "Don’t Care Conditions",
          "Product of Sums Method",
          "Product of Sums Simplification",
          "Hazards and Hazard Covers",
          "HDL Implementation Models",
        ],
      },
      {
        title: "Data Processing Circuits(5 hours)",
        topics: [
          "Multiplexetures",
          "Demultiplexetures",
          "Decoder",
          "BCD-to-Decimal Decoders",
          "Seven-Segment Decoders",
          "Encoder",
          "Exclusive-OR Gates",
          "Parity Generators and Checkers",
          "Magnitude Comparator",
          "Read-Only Memory",
          "Programmable Array Logic",
          "Programmable Logic Arrays",
          "Troubleshooting with a Logic Problems",
          "HDL Implementation of Data Processing Circuits",
        ],
      },
      {
        title: "Arithmetic Circuits(5 hours)",
        topics: [
          "Binary Addition",
          "Binary Subtraction",
          "Unsigned Binary Numbers",
          "Sign-Magnitude Numbers",
          "2’s Complement Representation",
          "2’s Complement Arithmetic",
          "Arithmetic Building Blocks",
          "The Adder-Subtracter",
          "Fast Adder",
          "Arithmetic Logic Unit",
          "Binary Multiplication and Division",
          "Arithmetic Circuits Using HDL",
        ],
      },
      {
        title: "Flip Flops(5 hours)",
        topics: [
          "RS Flip-Flops",
          "Gated Flip-Flops",
          "Edge-Triggered RS Flip-Flops",
          "Egde Triggered D Flip-Flops",
          "Egde Triggered JK Flip-Flops",
          "Flip-Flop Timing",
          "JK Mater- Slave Flip-Flops",
          "Switch Contacts Bounds Circuits",
          "Various Representation of Flip-Flops",
          "Analysis of Sequencial Circuits",
        ],
      },
      {
        title: "Registers(2 hours)",
        topics: [
          "Types of Registers",
          "Serial In–Serial Out",
          "Serial In–Parallel Out",
          "Parallel In–Serial Out",
          "Parallel In–Parallel Out",
          "Applications of Shift Registers",
        ],
      },
      {
        title: "Counters(5 hours)",
        topics: [
          "Asynchronous Counters",
          "Decoding Gates",
          "Synchronous Counters",
          "Changing the Counter Modulus",
          "Decade Counters",
          "Presettable Counters",
          "Counter Design as a Synthesis Problem",
          "A Digital Clock",
        ],
      },
      {
        title: "Sequential Machines(8 hours)",
        topics: [
          "Synchronous Machines:- Clock Driven Models and State Diagrams,Transition tables, Redundant States,Binary Assignment,Use of Flip-Flops in realizing the models,",
          "Asynchronous Machines:- Hazards in Asynchronous System and Use of Redundant Branch,Allowable Transitions,Flow tables and Merger Diagrams,Excitation Maps and Realization of the models,",
        ],
      },
      {
        title: "Digital Integrate Circuits(4 hours)",
        topics: [
          "Switching Circuits",
          "7400 TTL",
          "TTL parameters",
          "TTL Overvew",
          "Open Collecter Gates",
          "Three-state TTL Devices",
          "External Drive for TTL Lods",
          "TTL Driving External Loads",
          "74C00 CMOS",
          "CMOS Characteristics",
          "TTL-to–CMOS Interface",
          "CMOS-to-TTL Interface",
        ],
      },
      {
        title: "Applications(2 hours)",
        topics: [
          "Multiplexing Displays",
          "Frequency Counters",
          "Time Measurement",
        ],
      },
    ],
    practicals: [
      "DeMorgan’s law and it’s familiarization with NAND and NOR gates",
      "Encoder, Decoder, and Multiplexer",
      "Familiarization with Binary Addition and Subtraction",
      "Construction of True Complement Generator",
      "Latches, RS, Master-Slave and T type flip flops",
      "D and JK type flip flops",
      "Ripple Counter, Synchronous counter",
      "Familiarization with computer package for logic circuit design",
      "Design digital circuits using hardware and software tools",
      "Use of PLAs and PLDs",
    ],
    references: [
      "Donald P. Leach, Albert Paul Malvino and  Goutam Saha, “ Digital Principles and Applications”, 6th edition , Tata McGraw-Hill, 2006",
      "David  J Comer “Digital Logic And State Machine Design” 3rd edition, Oxfored University Press, 2002",
      "William I. Fletcher “An Engineering Approach  to Digital Design” Printice Hall of India, New Delhi 1990",
      "William H. Gothmann, “Digital Electronics, An Introduction to Theory and Practice”, 2nd edition, PHI, 2009",
    ],
    evaluationScheme:
      '<table border="1" cellspacing="0" cellpadding="0"> <tbody> <tr> <td width="63" valign="top"> <p align="center"><b>Chapters</b></p> </td> <td width="65" valign="top"> <p align="center"><b>Hours</b></p> </td> <td width="151" valign="top"> <p align="center"><b>Marks distribution*</b></p> </td> </tr> <tr> <td width="63"> <p align="center">1</p> </td> <td width="65"> <p align="center">3</p> </td> <td width="151"> <p align="center">6</p> </td> </tr> <tr> <td width="63"> <p align="center">2</p> </td> <td width="65"> <p align="center">1</p> </td> <td width="151"> <p align="center">4</p> </td> </tr> <tr> <td width="63"> <p align="center">3</p> </td> <td width="65"> <p align="center">5</p> </td> <td width="151"> <p align="center">8</p> </td> </tr> <tr> <td width="63"> <p align="center">4</p> </td> <td width="65"> <p align="center">5</p> </td> <td width="151"> <p align="center">10</p> </td> </tr> <tr> <td width="63"> <p align="center">5</p> </td> <td width="65"> <p align="center">5</p> </td> <td width="151"> <p align="center">8</p> </td> </tr> <tr> <td width="63"> <p align="center">6</p> </td> <td width="65"> <p align="center">5</p> </td> <td width="151"> <p align="center">8</p> </td> </tr> <tr> <td width="63"> <p align="center">7</p> </td> <td width="65"> <p align="center">2</p> </td> <td width="151"> <p align="center">4</p> </td> </tr> <tr> <td width="63"> <p align="center">8</p> </td> <td width="65"> <p align="center">5</p> </td> <td width="151"> <p align="center">8</p> </td> </tr> <tr> <td width="63"> <p align="center">9</p> </td> <td width="65"> <p align="center">8</p> </td> <td width="151"> <p align="center">12</p> </td> </tr> <tr> <td width="63"> <p align="center">10</p> </td> <td width="65"> <p align="center">4</p> </td> <td width="151"> <p align="center">8</p> </td> </tr> <tr> <td width="63"> <p align="center">11</p> </td> <td width="65"> <p align="center">2</p> </td> <td width="151"> <p align="center">4</p> </td> </tr> <tr> <td width="63"> <p align="center">Total</p> </td> <td width="65"> <p align="center">45</p> </td> <td width="151"> <p align="center">80</p> </td> </tr> </tbody> </table>',
  },
  {
    id: "computer-third-electronicdevicesandcircuits",
    title: "Electronic Devices and Circuits",
    objective:
      "To introduce the fundamentals of analysis of electronic circuits. To provide basic understanding of semiconductor devices and analog integrated circuits",
    chapters: [
      {
        title: "Diodes(5 hours)",
        topics: [
          "The Ideal Diode",
          "Terminal Characteristics of Junction Diodes",
          "Physical Operation of Diodes",
          "Analysis of Diode Circuits",
          "Small Signal Model and Its Application",
          "Operation in the Reverse Breakdown Region-Zener Diodes",
        ],
      },
      {
        title: "The Bipolar Junction Transistor(10 hours)",
        topics: [
          "Operation of the npn transistor in the Active Mode",
          "Graphical Representation of Transistor Characteristics",
          "Analysis of Transistor Circuits at DC",
          "Transistor as an Amplifier",
          "Small Signal Equivalent Circuit Models",
          "Graphical Load Line Analysis",
          "Biasing BJT for Discrete-Circuit Design",
          "Basic Single-Stage BJT Amplifier Configurations (C-B, C-E, C-C)",
          "Transistor as a Switch–Cut off and Saturation",
          "A General Large-Signal Model for the BJT: The Ebers-Moll Model",
        ],
      },
      {
        title: "Field-Effect Transistor(9 hours)",
        topics: [
          "Structure and Physical Operation of Enhancement-Type MOSFET",
          "Current-Voltage Characteristics of Enhancement-Type MOSFET",
          "The Depletion-Type MOSFET",
          "MOSFET Circuits at DC",
          "MOSFET as an Amplifier",
          "Biasing in MOS Amplifier Circuits",
          "Junction Field-Effect Transistor",
        ],
      },
      {
        title: "Output Stages and Power Amplifiers(9 hours)",
        topics: [
          "Classification of Output Stages",
          "Class A Output Stage",
          "Class B Output Stage",
          "Class AB Output Stage",
          "Biasing the Class AB Stage",
          "Power BJTs",
          "Transformer-Coupled Push-Pull Stages*",
          "Tuned Amplifiers",
        ],
      },
      {
        title: "Signal Generator and Waveform-Shaping Circuits(6 hours)",
        topics: [
          "Basic Principles of Sinusoidal Oscillator",
          "Op Amp-RC Oscillator Circuits",
          "LC and Crystal Oscillators",
          "Generation of Square and Triangular Waveforms Using Astable Multivibrators",
          "Integrated Circuit Timers",
          "Precision Rectifier Circuits",
        ],
      },
      {
        title: "Power Supplies, Breakdown Diodes, and Voltage Regulators",
        topics: [
          "Unregulated Power Supply",
          "Bandgap Voltage Reference, A Constant Current Diodes",
          "Transistor Series Regulators",
          "Improving Regulator Performance",
          "Current Limiting",
          "Integrated Circuit Voltage Regulator",
        ],
      },
      {
        title: "(6 hours)",
        topics: [
          "Unregulated Power Supply",
          "Bandgap Voltage Reference, A Constant Current Diodes",
          "Transistor Series Regulators",
          "Improving Regulator Performance",
          "Current Limiting",
          "Integrated Circuit Voltage Regulator",
        ],
      },
    ],
    practicals: [
      "Bipolar Junction Transistor Characteristics and Single Stage Amplifier",
      "Field-Effect Transistor Characteristics and Single Stage Amplifier",
      "Power Amplifiers",
      "Relaxation Oscillator and Sinusoidal Oscillator",
      "Series and Shunt Voltage Regulators",
    ],
    references: [
      "A.S.Sedra and K.C.Smith, “Microelectronic Circuits”, 6th Edition, Oxford University Press, 2006",
      "David A.Bell,  “ Electronics Device and Circuits ”, PHI; 3rd Edition, 1999.",
      "Robert Boylestad and Louis Nashelsky, “ Electronic Device and Circuit Theory”, PHI;  9th Edition, 2007",
      "Thomas L. Floyd, “Electronic Devices”, 8th Edition, Pearson Education Inc., 2007",
      "Mark N. Horenstein, “Microelectronic Circuits and Devices”, PHI; 2nd Edition, 1997",
      "Paul Horowitz and Winfield Fill, “The Art of Electornics”, Cambridge Publication; 2 Edition",
      "Jacob Millman and Christos C. Halkias,and Satyabrata Jit “Millman’s Electronic Device and Circuits”, Tata McGraw- Hill; 2nd Edition, 2007",
    ],
    evaluationScheme:
      '<table border="1" cellspacing="0" cellpadding="0"> <tbody> <tr> <td width="90" valign="top"> <b> <p align="center">Chapters</p> </b> </td> <td width="90" valign="top"> <p align="center"><b>Hours</b></p> </td> <td width="138" valign="top"> <p align="center"><b>Marks distribution*</b></p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">1</p> </td> <td width="90" valign="top"> <p align="center">6</p> </td> <td width="138" valign="top"> <p align="center">8</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">2</p> </td> <td width="90" valign="top"> <p align="center">10</p> </td> <td width="138" valign="top"> <p align="center">16</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">3</p> </td> <td width="90" valign="top"> <p align="center">9</p> </td> <td width="138" valign="top"> <p align="center">16</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">4</p> </td> <td width="90" valign="top"> <p align="center">9</p> </td> <td width="138" valign="top"> <p align="center">14</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">5</p> </td> <td width="90" valign="top"> <p align="center">6</p> </td> <td width="138" valign="top"> <p align="center">8</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">6</p> </td> <td width="90" valign="top"> <p align="center">6</p> </td> <td width="138" valign="top"> <p align="center">8</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">1,2, 3, 4, 5, 6</p> </td> <td width="90" valign="top"> <p align="center">&nbsp;</p> </td> <td width="138" valign="top"> <p align="center">10</p> </td> </tr> <tr> <td width="90" valign="top"> <p align="center">Total</p> </td> <td width="90" valign="top"> <p align="center">45</p> </td> <td width="138" valign="top"> <p align="center">80</p> </td> </tr> </tbody> </table>',
  },
];

export default ksThirdSemComputer;
