const ksFirstSemCivil = [
  {
    id: "civil-first-engineeringdrawingi",
    title: "Drawing I",
    objective:
      "To develop basic projection concepts with reference to points, lines, planes and geometrical solids. Also to develop sketching and drafting skills to facilitate communication.",
    chapters: [
      {
        title:
          "Instrumental Drawing, Technical Lettering Practices and Techniques (2 hours)",
        topics: [
          "Equipment and materials",
          "Description of drawing instruments, auxiliary equipment and drawing materials",
          "Techniques of instrumental drawing",
          "Pencil sharpening, securing paper, proper use of T- squares, triangles, scales dividers, compasses, erasing shields,  French curves, inking pens",
          "Lettering strokes, letter proportions, use of pencils and pens, uniformity and appearance of letters, freehand techniques, inclined and vertical letters and numerals, upper and lower cases, standard English lettering forms",
        ],
      },
      {
        title: "Dimensioning (2 hours)",
        topics: [
          "Fundamentals and techniques",
          "Size and location dimensioning, SI conversions",
          "Use of scales, measurement units, reducing and enlarging  drawings",
          "Placement of dimensions: aligned and unidirectional",
        ],
      },
      {
        title: "Applied Geometry (6 hours)",
        topics: [
          "Plane geometrical construction:  Proportional division of lines, arc  & line tangents",
          "Methods  for drawing standard curves such as ellipses, parabolas, hyperbolas, involutes, spirals, cycloids and helices (cylindrical and conical)",
          "Techniques to reproduce a given drawing (by construction)",
        ],
      },
      {
        title: "Basic Descriptive Geometry (14 hours)",
        topics: [
          "Introduction to Orthographic projection, Principal Planes, Four Quadrants or Angles",
          "Projection of points on first, second, third and fourth quadrants",
          "Projection of Lines: Parallel to one of the principal plane, Inclined to one of the principal plane and parallel to other, Inclined to both principal planes",
          "Projection Planes: Perpendicular to both principal planes, Parallel to one of the principal planes and Inclined to one of the principal planes, perpendicular to other and Inclined to both principal planes",
          "True length of lines: horizontal, inclined and oblique lines",
          "Rules for parallel and perpendicular lines",
          "Point view or end view of a line",
          "Shortest distance from a point to a line",
          "Edge View and True shape of an oblique plane",
          "Angle between two intersecting lines",
          "Intersection of a line and a plane",
          "Angle between a line and a plane",
          "Dihedral angle between two planes",
          "Shortest distance between  two skew lines",
          "Angle between two non- intersecting (skew) lines",
        ],
      },
      {
        title: "Multi view (orthographic) projections (18 hours)",
        topics: [
          "Orthographic Projections: First and third angle projection ",
          "Orthographic Projections: Principal views (methods for obtaining orthographic views, Projection of lines,  angles and plane surfaces, analysis in three views, projection of curved lines and surfaces, object orientation and selection of views for best representation, full and hidden lines)",
          "Orthographic Projections: Orthographic drawings (making an orthographic drawing, visualizing objects (pictorial view) from the given views)",
          "Orthographic Projections: Interpretation of adjacent areas, true-length lines, representation of holes, conventional practices",
          "Sectional Views: Full, half, broken revolved, removed (detail) sections,  phantom of hidden section,  Auxiliary sectional views,  specifying cutting planes for sections, conventions for hidden lines, holes, ribs, spokes",
          "Auxiliary views: Basic concept and use, drawing methods and types, symmetrical and unilateral auxiliary views.  Projection of curved lines and boundaries, line of intersection between two planes, true size of dihedral angles, true size and shape of plane surfaces",
        ],
      },
      {
        title: "Developments and Intersections (18 hours)",
        topics: [
          "Introduction and Projection of Solids",
          "Developments: general concepts and practical considerations, development of a right or oblique prism, cylinder, pyramid, and cone, development of truncated pyramid and cone,  Triangulation method  for approximately developed surfaces, transition pieces for connecting different shapes, development of a sphere",
          "Intersections: lines of intersection of geometric surfaces, piercing point of a line and a geometric solid, intersection lines of two planes,  intersections of -prisms and pyramids, cylinder and an oblique plane. Constructing a development using auxiliary views, intersection of - two cylinders, a cylinder & a cone",
        ],
      },
    ],
    references: [
      "“Fundamentals of Engineering Drawing”, W. J. Luzadder, Prentice Hall",
      "“Engineering Drawing and Graphic Technology”, T. E. French, C. J. Vierck, and R. J. Foster, Mc Graw Hill Publshing Co",
      "“Technical Drawing”, F. E. Giescke, A . Mitchell, H. C. Spencer and J. T. Dygdone, Macmillan Publshing Co",
      "“Elementary Engineering Drawing”, N. D. Bhatt, Charotar Publshing House, India",
      "“A Text Book of Engineering Drawing”, P. S. Gill, S. K. Kataria and Sons, India",
      "“A Text Book of Engineering Drawing”, R. K. Dhawan, S. Chand and Company Limited, India",
    ],
    books: [
      {
        title: "Engineering Drawing I - Mahesh Chandra Luitel",
        path: "/books/engineering_drawing.pdf",
      },
    ],
    old_questions: "/old_questions/first_sem/engineering_drawing.pdf",
  },
  {
    id: "civil-first-engineeringmathematicsi",
    title: "Engineering Maths I",
    objective: "",
    chapters: [
      {
        title: "Derivatives and their Applications",
        topics: [
          "Introduction",
          "Higher order derivatives",
          "Mean value theorem: Rolle’s theorem",
          "Mean value theorem: Lagrange’s mean value theorem",
          "Mean value theorem: Cauchy’s mean value theorem",
          "Power series of single valued function: Taylor’s series",
          "Power series of single valued function: Maclaurin’s series",
          "Indeterminate forms: L Hospital rule",
          "Asymptotes to Cartesian and polar curves",
          "Pedal equations to Cartesian and polar curves; curvature and radius of curvature",
        ],
      },
      {
        title: "Integration and its application",
        topics: [
          "Introduction",
          "Definite integrals and their properties",
          "Improper integrals",
          "Differentiation under integral signs",
          "Reduction formula: Beta Gama functions",
          "Application of integrals for finding areas arc length, surface and solid of revolution in the plane for Cartesian and polar curves",
        ],
      },
      {
        title: "Plane Analytic Geometry",
        topics: [
          "Transformation of coordinates: Translation and rotation",
          "Ellipse and hyperbola: Standard forms, tangent and normal",
          "General equation of conics in Cartesian and polar forms",
        ],
      },
      {
        title: "Ordinary Differential equations and their applications",
        topics: [
          "First order and first degree differential equations",
          "Homogenous differential equations",
          "Linear differential equations",
          "Equation reducible to linear differential equations: Bernoulli’s equation",
          "First order and higher degree differential equation: Clairaut’s equation",
          "Second order and first degree linear differential equations with constant coefficients",
          "Second order and first degree linear differential equations with variable coefficients: Cauchy’s equation",
          "Applications in Engineering field",
        ],
      },
    ],
    references: [
      "Erwin Kreyszig, Advance Engineering Mathematics , John Wiley and Sons Inc",
      "Thomas,Finney,Calculus and Analytical geometry Addison- Wesley",
      "M. B. Singh, B. C. Bajrachrya, Differential calculus, Sukunda Pustak Bhandar,Nepal",
      "M. B. Singh, S. P. Shrestha, Applied Mathematics",
      "G.D. Pant, G. S. Shrestha, Integral Calculus and Differential Equations, Sunila Prakashan,Nepal",
      "M. R. Joshi, Analytical Geometry, SukundaPustak Bhandar, Nepal",
      "S. P. Shrestha, H. D. Chaudhary, P. R. Pokharel, A Textbook of Engineering Mathematics – Vol I",
      "Santosh Man Maskey, Calculus, Ratna Pustak Bhandar, Nepal",
    ],
    books: [
      {
        title: "A complete solution to Engineering Mathematics I",
        description: "",
        path: "/books/maths.pdf",
      },
    ],
    old_questions: "/old_questions/first_sem/mathematics.pdf",
  },
  {
    id: "civil-first-thermodynamicsandheattransfer",
    title: "Fundamentals of Thermodynamics and Heat Transfer",
    objective:
      "To develop basic concepts, laws of thermodynamics and heat transfer and their applications.",
    chapters: [
      {
        title: "Introduction(3 hours)",
        topics: [
          "Definition and Scope of Engineering Thermodynamics",
          "Value of energy to society",
          "Microscopic versus Macroscopic Viewpoint",
          "Concepts and Definitions:- System, Surroundings, Boundary and Universe; Closed Systems, Open Systems, and Isolated Systems,Thermodynamic Properties: Intensive, Extensive and Specific Property,Thermodynamic Equilibrium,State, Process, and Path, Cyclic Process, Quasi-equilibrium Process, Reversible and Irreversible Process,Common Properties: Pressure, Specific Volume, Temperature,",
          "Zeroth Law of Thermodynamics, Equality of Temperature",
        ],
      },
      {
        title: "Energy and Energy Transfer(3 hours)",
        topics: [
          "Energy and its Meaning",
          "Stored Energy and Transient Energy: Total Energy",
          "Energy Transfer:- Heat Transfer,Work Transfer,",
          "Expressions for displacement Work Transfer",
          "Power",
        ],
      },
      {
        title: "Properties of Common Substances(6 hours)",
        topics: [
          "Pure Substance and State Postulate",
          "Ideal Gas and Ideal Gas Relations",
          "Two Phase (Liquid and Vapor) Systems: Phase Change, Subcooled Liquid, Saturated Liquid, Wet Mixture, Critical Point, Quality, Moisture Content, Saturated Vapor and Superheated Vapor",
          "Properties of Two Phase Mixture",
          "Other Thermodynamic Properties: Internal Energy, Enthalpy and Specific Heats",
          "Development of Property Data: Graphical Data Presentation and Tabular Data Presentation",
        ],
      },
      {
        title: "First Law of Thermodynamics(9 hours)",
        topics: [
          "First Law of Thermodynamics for Control Mass: First Law of Thermodynamics for Control Mass Undergoing Cyclic Process",
          "First Law of Thermodynamics for Control Volume",
          "Control Volume Analysis: Steady State Analysis and Unsteady State Analysis",
          "Control Volume Application: Steady and Unsteady Work Applications and Steady and Unsteady Flow Applications",
          "Other Statements of the First Law",
        ],
      },
      {
        title: "Second Law of Thermodynamics(9 hours)",
        topics: [
          "Necessity of Formulation of Second Law",
          "Entropy and Second Law of Thermodynamics for an Isolated System",
          "Reversible and Irreversible Processes",
          "Entropy and Process Relation for an Ideal Gases and Incompressible Substances",
          "Control Mass and Control Volume Formulation of Second Law",
          "Isentropic Process for an Ideal Gas and for an Incompressible Substances",
          "Carnot Cycle, Carnot Efficiency, Heat Engine and Thermal Efficiency, Heat Pump, Refrigerator and coefficient of Performance(COP)",
          "Kelvin-Planck and Clausius Statements of the Second Law of Thermodynamics and their Equivalence",
        ],
      },
      {
        title: "Thermodynamic Cycles(9 hours)",
        topics: [
          "Classification of Cycles",
          "Air Standard Analysis:- Otto Cycle,Diesel Cycle,Brayton Cycle,Rankine Cycle,Vapor Compression Refrigeration Cycle,",
        ],
      },
      {
        title: "Introduction to Heat Transfer (6 hours)",
        topics: [
          "Basic Concepts and Modes of Heat Transfer",
          "One dimensional steady state heat conduction through a plane wall",
          "Radial steady state heat conduction through a hollow cylinder",
          "Heat flow through composite structures:- Composite Plane Wall,Multilayer Ttubes,",
          "Electrical Analogy for Thermal Resistance",
          "Combined Heat Transfer and Overall Heat Transfer Coefficient for Plane Wall and Tube",
          "Nature of Convection: Free and Forced Convection",
          "Heat Radiation, Stefan's Law, Absorptivity, Reflectivity and Transmisivity; Black Body, White Body and Gray Body",
        ],
      },
    ],
    practicals: [
      "Temperature Measurements",
      "Experiment related to First Law",
      "Heat Pump",
      "Heat Conduction",
      "Heat Radiation",
    ],
    references: [
      "“Engineering Thermodynamics”, E. Rathakrishnan, Tata Mc Graw Hill.",
      '“Fundamentals of Engineering Thermodynamics", J. R. Howell & R. O. Buckius, McGraw Hill Publishers',
      "“Fundamentals of Thermodynamics”, V. Wylen, Sonntag & Borgnakke, 6th Edition, Wiley",
      '“Fundamentals of Engineering Thermodynamics", M. J. Moran & H. N. Shapiro, 5th Edition, John Wiley & Sons, Inc.',
      '"Thermodynamics: An Engineering Approach", Y. A. Cengel & M.A. Boles,5th Edition, McGraw-Hill, 2006',
      '"Heat Transfer", J. P. Holman, McGraw-Hill',
      '"Heat Transfer: A Practical Approach", Y. A. Cengel,2nd Edition, McGraw-Hill',
    ],
    evaluationScheme:
      '<table border="1" cellspacing="0" cellpadding="0" width="276"> <tbody> <tr> <td width="62" valign="center"> <b> <p align="center">Chapter</p> </b> </td> <td width="69" valign="center"> <p align="center"><b>Hours</b></p> </td> <td width="137" valign="center"> <p align="center"><b>Marks distribution *</b></p> </td> </tr> <tr> <td width="62" valign="top"> <p align="center">1</p> </td> <td width="69" valign="top"> <p align="center">4</p> </td> <td width="137" valign="top"> <p align="center">10</p> </td> </tr> <tr> <td width="62" valign="top"> <p align="center">2</p> </td> <td width="69" valign="top"> <p align="center">4</p> </td> <td width="137" valign="top"> <p align="center">4</p> </td> </tr> <tr> <td width="62" valign="top"> <p align="center">3</p> </td> <td width="69" valign="top"> <p align="center">6</p> </td> <td width="137" valign="top"> <p align="center">12</p> </td> </tr> <tr> <td width="62" valign="top"> <p align="center">4</p> </td> <td width="69" valign="top"> <p align="center">8</p> </td> <td width="137" valign="top"> <p align="center">14</p> </td> </tr> <tr> <td width="62" valign="top"> <p align="center">5</p> </td> <td width="69" valign="top"> <p align="center">9</p> </td> <td width="137" valign="top"> <p align="center">14</p> </td> </tr> <tr> <td width="62" valign="top"> <p align="center">6</p> </td> <td width="69" valign="top"> <p align="center">8</p> </td> <td width="137" valign="top"> <p align="center">14</p> </td> </tr> <tr> <td width="62" valign="top"> <p align="center">7</p> </td> <td width="69" valign="top"> <p align="center">6</p> </td> <td width="137" valign="top"> <p align="center">12</p> </td> </tr> <tr> <td width="62" valign="top"> <p align="center">Total</p> </td> <td width="69" valign="top"> <p align="center">45</p> </td> <td width="137" valign="top"> <p align="center">80</p> </td> </tr> </tbody> </table>',
  },
  {
    id: "civil-first-engineeringchemistry",
    title: "Engineering Chemistry",
    objective:
      "To develop the basic concepts of Physical Chemistry, Inorganic Chemistry and Organic Chemistry relevant to problems in engineering.",
    chapters: [
      {
        title: "Electro-chemistry and Buffer(6 hours)",
        topics: [
          "Electro-Chemical cells",
          "Electrode Potential and Standard Electrode Potential",
          "Measurement of Electrode Potential",
          "Nernst equation",
          "EMF of Cell",
          "Application of Electrochemical and Electrolytic cells",
          "Electrochemical Series and its Application",
          "Buffer: Its type and mechanism",
          "Henderson’s equation for pH of buffer and related problems",
          "Corrosion and its type",
          "Factors influencing Corrosion",
          "Prevention of Corrosion",
        ],
      },
      {
        title: "Catalyst(4 hours)",
        topics: [
          "Introduction",
          "Action of Catalyst(Catalytic Promoters and Catalytic Poisons)",
          "Characteristics of Catalyst",
          "Types of Catalyst",
          "Theories of Catalysis",
          "Industrial Applications of Catalysts",
        ],
      },
      {
        title: "Environmental Chemistry(5 hours)",
        topics: [
          "Air Pollution",
          "Air Pollutants i) Gases:SOx, NOx, CO, CO2, O3 and Hydrocarbons ii)Particulates dust, smoke and fly ash",
          "Effects of Air Pollutants on human beings and their possible remedies",
          "Ozone depletion and its Photochemistry",
          "Water Pollution(Ref of Surface Water and Pond Water)",
          "Water Pollutants(Ref of Surface Water), their adverse effect and remedies",
          "Soil Pollution",
          "Pollutants of Soil, their adverse effects and possible remedies",
        ],
      },
      {
        title: "Engineering Polymers(6 hours)",
        topics: [
          "Inorganic Polymers",
          "General properties of Inorganic Polymers:- Polyphosphazines,Sulpher Based Polymers,Chalcogenide Glasses,Silicones,",
          "Organic Polymers",
          "Types of Organic Polymers",
          "Preparation and application of\ni) Polyurethane ii) Polystyrene iii) Polyvinylchloride iv) Teflon v) Nylon 6,6 and vi) Bakelite vii) Epoxy Resin viii) Fiber Reinforced Polymer",
          "Concept of Bio-Degradable, Non-Biodegradable and Conducting polymers",
        ],
      },
      {
        title: "3-d Transition elements and their applications(5 hours)",
        topics: [
          "Introduction",
          "Electronic Configuration",
          "Variable Oxidation states",
          "Complex formation tendency",
          "Color formation",
          "Magnetic properties",
          "Alloy formation",
          "Applications of 3-d transition elements",
        ],
      },
      {
        title: "Coordination Complexes(5 hours)",
        topics: [
          "Introduction",
          "Terms used in Coordination Complexes",
          "Werner’s Theory Coordination Complexes",
          "Sidgwick’s Model and Sidgwick’s effective atomic number rule",
          "Nomenclature of Coordination compounds(Neutral type, simple cation and complex anion and complex cation and simple anion type)",
          "Valence Bond Theory of Complexes",
          "Application of valence bond theory in the formation of i) Tetrahedral Complexes\nii) Square planar Complexes and iii) Octahedral Complexes",
          "Limitations of Valence Bond Theory",
          "Applications of Coordination Complexes",
        ],
      },
      {
        title: "Explosives(3 hours)",
        topics: [
          "Introduction",
          "Types of explosives: Primary, Low and High explosives",
          "Preparation and application of TNT, TNG, Nitrocellulose and Plastic explosives",
        ],
      },
      {
        title: "Lubricants and Paints(2 hours)",
        topics: [
          "Introduction",
          "Function of Lubricants",
          "Classification of Lubricants(Oils, Greases and Solid)",
          "Paints",
          "Types of Paint",
          "Application of Paints",
        ],
      },
      {
        title: "Stereochemistry(4 hours)",
        topics: [
          "Introduction",
          "Geometrical Isomerism(Cis-Trans Isomerism), Z and E concept of Geometrical Isomerism",
          "Optical Isomerism with reference to two asymmetrical carbon center molecules",
          "Terms Optical activity, Enantiomers, Diastereomers, Meso structures, Racemic mixture and Resolution",
        ],
      },
      {
        title: "Reaction Mechanism in Organic reactions(4 hours)",
        topics: [
          "Substitution reaction",
          "Types of substitution reaction SN1 and SN2",
          "Elimination reaction",
          "Types of elimination reaction E1 and E2",
          "Factors governing SN1, SN2, E1 and E2 reaction mechanism path",
        ],
      },
    ],
    practicals: [
      "Compare the alkalinity of different water samples by double indicator method(6 Periods)",
      "Determine the temporary and permanent hardness of water by EDTA Complexo-metric method(3 Periods)",
      "Determine residual and combined chlorine present in the chlorinated sample of water by Iodometric method(6 Periods)",
      "Prepare organic polymer nylon 6,6; Bakelite in the laboratory(3 Periods)",
      "Determine the pH of different sample of buffer solution by universal indicator method(6 Periods)",
      "Prepare inorganic complex in the laboratory(3 Periods)",
      "Determine surface tension of the given detergent solution and compare its cleansing power with other detergent solutions(6 Periods)",
      "Construct an electrochemical cell in the laboratory and measure the electrode potential of it(3 Periods)",
      "Estimate the amount of iron present in the supplied sample of ferrous salt using standard potassium permanganate solution(redox titration)(6 Periods)",
    ],
    references: [
      '"Engineering Chemistry",by Jain and Jain',
      '"A Text Book of Engineering Chemistry",by Shashi Chawala',
      '"A New Concise Inorganic Chemistry by",J.D. Lee',
      '"Principles of Physical Chemistry",by Marron and Prutton',
      '"Essential of Physical Chemistry",by Bahl and Tuli',
      '"Advanced Inorganic Chemistry Vol 1 and 2",by Satya Prakash and Tuli',
      '"Organic chemistry",by Morrison and Boyd',
      '"Selected Topics in Physical Chemistry",by Moti Kaji Sthapit',
      '"Environmental Engineering",by Peavy, Rowe and Tchobanoglous',
    ],
    evaluationScheme:
      '<table border="1" cellspacing="0" cellpadding="0" width="287"> <tbody> <tr> <td width="73"> <p align="center"> <b>Chapter</b></p> </td> <td width="69"> <p align="center"><b>Hours</b></p> </td> <td width="137"> <p align="center"><b>Marks distribution*</b></p> </td> </tr> <tr> <td width="73"> <p align="center">1</p> </td> <td width="69"> <p align="center">6</p> </td> <td width="137"> <p align="center">10</p> </td> </tr> <tr> <td width="73"> <p align="center">2</p> </td> <td width="69"> <p align="center">4</p> </td> <td width="137"> <p align="center">5 or 10</p> </td> </tr> <tr> <td width="73"> <p align="center">3</p> </td> <td width="69"> <p align="center">5</p> </td> <td width="137"> <p align="center">10</p> </td> </tr> <tr> <td width="73"> <p align="center">4</p> </td> <td width="69"> <p align="center">6</p> </td> <td width="137"> <p align="center">10</p> </td> </tr> <tr> <td width="73"> <p align="center">5</p> </td> <td width="69"> <p align="center">5</p> </td> <td width="137"> <p align="center">10</p> </td> </tr> <tr> <td width="73"> <p align="center">6</p> </td> <td width="69"> <p align="center">5</p> </td> <td width="137"> <p align="center">10</p> </td> </tr> <tr> <td width="73"> <p align="center">7</p> </td> <td width="69"> <p align="center">3</p> </td> <td width="137"> <p align="center">5</p> </td> </tr> <tr> <td width="73"> <p align="center">8</p> </td> <td width="69"> <p align="center">3</p> </td> <td width="137"> <p align="center">5</p> </td> </tr> <tr> <td width="73"> <p align="center">9</p> </td> <td width="69"> <p align="center">4</p> </td> <td width="137"> <p align="center">5 or 10</p> </td> </tr> <tr> <td width="73"> <p align="center">10</p> </td> <td width="69"> <p align="center">4</p> </td> <td width="137"> <p align="center">5 or 10</p> </td> </tr> <tr> <td width="73"> <p align="center">Total</p> </td> <td width="69"> <p align="center">45</p> </td> <td width="137"> <p align="center">80</p> </td> </tr> </tbody> </table>',
  },
  {
    id: "civil-first-workshoptechnology",
    title: "Workshop Technology",
    objective:
      "To impart knowledge and skill components in the field of basic workshop technology.To be familiar with different hand and machine tools required for manufacturing simple metal components and articles.",
    chapters: [
      {
        title: "General safety Considerations(2 hours)",
        topics: [
          "Bench Tools",
          "Machinist’s Hammers",
          "Screw Drivers",
          "Punches",
          "Chisels",
          "Scrapers",
          "Scribers",
          "Files",
          "Pliers and Cutters",
          "Wrenches",
          "Hacksaw",
          "Bench Vise",
          "Hand Drill",
          "Taps and Dies",
          "Hand Shears",
          "Rules,Tapes and Squares",
          "Soldering Iron",
          "Rivets",
        ],
      },
      {
        title: "Hand Working Operations(1 hour)",
        topics: [
          "Sawing",
          "Filing",
          "Threading",
          "Scribing",
          "Shearing",
          "Soldering",
          "Riveting",
        ],
      },
      {
        title: "Measuring and Gauging(1 hour)",
        topics: [
          "Introduction",
          "Semi–Precision Tools: Calipers, Depth Gauge, Feeler Gauge",
          "Precision Tools: Micrometers, Vernier Calipers, Vernier Height Gauge, Telescopic Gauge, Hole Gauge, Bevel Protractor, Dial Indicator, Gauge Blocks and Surface Plate",
        ],
      },
      {
        title: "Drills and Drilling Processes(1 hour)",
        topics: [
          "Introduction",
          "Types of Drill Presses",
          "Work Holding Devices and Accessories",
          "Cutting Tools",
          "Geometry of Drill Bits",
          "Grinding of Drill Bits",
          "Operations: Drilling, Counter-boring, Counter-sinking, Reaming, Honning, Lapping",
          "Cutting Speeds",
          "Drilling Safety",
        ],
      },
      {
        title: "Machine Tools(4 hours)",
        topics: [
          "General Safety Considerations",
          "Engine Lathes:- Introduction,Physical Construction,Types of Lathe,Lathe Operations: Facing, Turning, Threading,",
          "Shapers:- Introduction,Types of Shapers,Physical Construction,General Applications,",
          "Milling Machines:- Introduction,Types of Milling Machines,Physical Construction,Milling Cutters: Plain, Side, Angle, End, Form,Milling Operations: Plain, Side, Angular, Gang, End, Form, Keyway,Work Holding Devices,Cutter Holding Devices,",
          "Grinding Machines:- Abrasives, Bonds, Grinding Wheels,Rough Grinders: Portable Grinders, Bench Grinders, Swing Frame Grinders, Abrasive Belt Grinders,Precision Grinders: Cylindrical Grinders, Surface Grinders,",
        ],
      },
      {
        title: "Material Properties(1 hour)",
        topics: [
          "Tool materials: Low, medium and high carbon steels; Hot and cold rolled steels; Alloy steels; Carbide and Ceramic materials",
          "Heat treating methods for steels: Annealing, Tempering, Normalizing, Hardening and Quenching",
          "Non–ferrous metals: Brass, Bronze, Aluminum; Comparative Properties",
        ],
      },
      {
        title: "Sheet Metal Works(1 hour)",
        topics: [
          "Introduction",
          "Sheet Metal Tools",
          "Marking and Layout",
          "Operations: Bending, Cutting, Rolling",
        ],
      },
      {
        title: "Foundry Practice(1 hour)",
        topics: [
          "Introduction",
          "Pattern Making",
          "Foundry Tools",
          "Core Making",
          "Melting Furnace – Cupola",
          "Sand Casting Process",
        ],
      },
      {
        title: "Forging Practice(1 hour)",
        topics: [
          "Introduction",
          "Forging Tools",
          "Operations: Upsetting, Drawing, Cutting, Bending, Punching",
          "Forging Presses and Hammers",
          "Advantages and Limitations",
        ],
      },
      {
        title: "Metal Joining(2 hours)",
        topics: [
          "Safety Considerations",
          "Introduction",
          "Soldering",
          "Brazing",
          "Welding: Gas Welding, Arc Welding, Resistance Welding, Tungsten Inert  Gas Welding (TIG), Metal Inert Gas Welding (MIG)",
        ],
      },
    ],
    practicals: [],
    references: [
      "“Shop Theory”, J. Anderson and E. E. Tatro, McGraw – Hill, 5th Edition, 1942",
      "“Machine shop operations and setups”, O. D. Lascoe, C. A. Nelson and H. W. Porter, American Technical society, 1973",
      "“Machine shop Practice – Vol. I” , Industrial Press, New York, 1971",
      "“Machine shop Practice – Vol. I” , Industrial Press, New York, 1971",
      "“ Technology of Machine Tools”, Mc Graw Hill – Ryerson, 3rd Edition",
      "“Machinery’s Handbook”, Oberg, Jones and Horton, 23rd Edition, Industrial Press, New York.",
      "“Elements of Workshop Technology - Vol. I ( Manufacturing Processes)” – S. K. Hajra Choudhury and A. K. Hajra Choudhury – Media Promoters and Publishers Pvt. Ltd. , Bombay, INDIA, Tenth Edition, 1993",
      "“Elements of Workshop Technology - Vol. II: (Machine Tools)” – S. K. Hajra Choudhury, S. K. Bose and A. K. Hajra Choudhury – Media Promoters and Publishers Pvt. Ltd. , Bombay, INDIA, Eight Edition, 1988",
      "“A Course in Workshop Technology - Vol. I” – Prof. B. S. Raghuwanshi – Dhanpat Rai and Co. (P) Ltd, Delhi, INDIA, Ninth Edition, 2002",
      "“A Course in Workshop Technology - Vol. II” – Prof. B. S. Raghuwanshi – Dhanpat Rai and Co. (P) Ltd, Delhi, INDIA, Ninth Edition, 2002",
      "“Workshop Technology - Vol. I” – H. S. Bawa – Tata Mc – Graw Hill publishing company Limited, New Delhi, INDIA,",
      "“Workshop Technology - Vol. II” – H. S. Bawa – Tata Mc – Graw Hill publishing company Limited, New Delhi, INDIA,",
      '"A text book of Workshop Technology" - R. S. Khurmi and J. K. Gupta - S. Chand and Company Ltd, New Delhi. INDIA',
    ],
    evaluationScheme: "",
  },
  {
    id: "civil-first-computerprogramming",
    title: "Computer Programming",
    objective:
      "To acquaint the student with computer software and high level programming languages. Emphasis will be given on developing computer programming skills using computer programming in C and FORTRAN languages.",
    chapters: [
      {
        title:
          "Overview of computer software & programming languages (2 hours)",
        topics: [
          "System software",
          "Application software",
          "General software features and recent trends",
          "Generation of programming languages",
          "Categorization of high level languages",
        ],
      },
      {
        title: "Problem solving using Computer (2 hours)",
        topics: [
          "Problem analysis",
          "Algorithm development and Flowchart",
          "Compilation and Execution",
          "Debugging and Testing",
          "Programming Documentation",
        ],
      },
      {
        title: "Introduction to  ‘C’ programming (3 hours)",
        topics: [
          "Character set, Keywords, and Data types",
          "Preprocessor Directives",
          "Constants and Variables",
          "Operators and statements",
        ],
      },
      {
        title: "Input and Output (2 hours)",
        topics: [
          "Formatted input/output",
          "Character input/output",
          "Programs using input/output statements",
        ],
      },
      {
        title: "Control statements(6 hours)",
        topics: [
          "Introduction",
          "The goto, if,  if … else, switch statements",
          "The while, do … while, for statements",
        ],
      },
      {
        title: "User-Defined Functions(4 hours)",
        topics: [
          "Introduction",
          "Function definition and return statement",
          "Function Prototypes",
          "Function invocation, call by value and call by reference, Recursive Functions",
        ],
      },
      {
        title: "Arrays and Strings (6 hours)",
        topics: [
          "Defining an Array",
          "One-dimensional Arrays",
          "Multi-dimensional Arrays",
          "Strings and string manipulation",
          "Passing Array and String to function",
        ],
      },
      {
        title: "Structures (4 hours)",
        topics: [
          "Introduction",
          "Processing a Structure",
          "Arrays of Structures",
          "Arrays within Structures",
          "Structures and Function",
        ],
      },
      {
        title: "Pointers (4 hours)",
        topics: [
          "Introduction",
          "Pointer declaration",
          "Pointer arithmetic",
          "Pointer and Array",
          "Passing Pointers to a Function",
          "Pointers and Structures",
        ],
      },
      {
        title: "Data Files (4 hours)",
        topics: [
          "Defining opening and closing a file",
          "Input/Output operations on Files",
          "Error handling during input/output operations",
        ],
      },
      {
        title: "Programming Language: FORTRAN (8 hours)",
        topics: [
          "Character set",
          "Data types, Constants and variables",
          "Arithmetic operations, Library Functions",
          "Structure of a Fortran Program",
          "Formatted and Unformatted Input/Output Statements",
          "Control Structures: Goto, Logical IF, Arithmetic IF, Do loops",
          "Arrays: one dimensional and two dimensional",
        ],
      },
    ],
    references: [
      "Kelly & Pohl, “A Book on C”, Benjamin/Cumming",
      "Brian W. Keringhan & Dennis M. Ritchie, “The ‘C’ Programming Language”, PHI",
      "Bryons S. Gotterfried, “Programming with C”, TMH",
      "Yashavant Kanetkar, “Let Us C”, BPB",
      "D. M. Etter, “Structured Fortran & for Engineers and Scientist”, The Benjamin/Cummings Publishing Company, Inc.",
      "Rama N. Reddy and Carol A. Ziegler, “FORTRAN 77 with Applications for Scientists and Engineers”, Jaico Publishing House",
      "Alexis Leon, Mathews Leon, “Fundamentals of Information Technology”, Leon Press and Vikas Publishing House",
    ],
    books: [
      {
        title: "Introduction to Programming using C - Jayaram",
        path: "/books/c_programming.pdf",
      },
    ],
    old_questions: "/old_questions/first_sem/c_programming.pdf",
  },
];

export default ksFirstSemCivil;
