const ksThirdSemComputer = [
  {
    id: "computer-third-engineeringmathiii",
    title: "Engineering Math III",
    objective: "",
    chapters: [
      {
        title: "1. Determinants and Matrices (11 hours)",
        topics: [
          "1.1. Determinant and its properties",
          "1.2. Solution of system of linear equations",
          "1.3. Algebra of matrices",
          "1.4. Complex matrices",
          "1.5. Rank of matrices",
          "1.6. System of linear equations",
          "1.7. Vector spaces",
          "1.8. Linear transformations",
          "1.9. Eigen value and Eigen vectors",
          "1.10. The Cayley-Hamilton theorem and its uses",
          "1.11. Diagonalization of matrices and its applications",
        ],
      },
      {
        title: "2. Line, Surface and Volume Integrals (12 hours)",
        topics: [
          "2.1. Line integrals",
          "2.2. Evaluation of line integrals",
          "2.3. Line integrals independent of path",
          "2.4. Surfaces and surface integrals",
          "2.5. Green’s theorem in the plane and its applications",
          "2.6. Stoke’s theorem (without proof) and its applications",
          "2.7. Volume integrals; Divergence theorem of Gauss (without proof) and its applications",
        ],
      },
      {
        title: "3. Laplace Transform (8 hours)",
        topics: [
          "3.1. Definitions and properties of Laplace Transform",
          "3.2. Derivations of basic formulae of Laplace Transform",
          "3.3. Inverse Laplace Transform: Definition and standard formulae of inverse Laplace Transform",
          "3.4. Theorems on Laplace transform and its inverse",
          "3.5. Convolution and related problems",
          "3.6. Applications of Laplace Transform to ordinary differential equations",
        ],
      },
      {
        title: "4. Fourier Series (5 hours)",
        topics: [
          "4.1. Fourier Series",
          "4.2. Periodic functions",
          "4.3. Odd and even functions",
          "4.4. Fourier series for arbitrary range",
          "4.5. Half range Fourier series",
        ],
      },
      {
        title: "5. Linear Programming (9 hours)",
        topics: [
          "5.1. System of Linear Inequalities in two variables",
          "5.2. Linear Programming in two dimensions: A Geometrical Approach",
          "5.3. A Geometric introduction to the Simplex method",
          "5.4. The Simplex method: Maximization with Problem constraints of the form “≤”",
          "5.5. The Dual: Maximization with Problem Constraints of the form “≥”",
          "5.6. Maximization and Minimization with mixed Constraints. The two- phase method (An alternative to the Big M Method)",
        ],
      },
    ],
  },
  {
    id: "computer-third-objectorientedprogramming",
    title: "Object Oriented Programming",
    objective: "",
    chapters: [
      {
        title: "Introduction to Object Oriented Programming (3 hours)",
        topics: [
          "Issues with Procedure Oriented Programming",
          "Basic of Object Oriented Programming (OOP)",
          "Procedure Oriented versus Object Oriented Programming",
          "Concept of Object Oriented Programming; Object; Class; Abstraction; Encapsulation; Inheritance; Polymorphism",
          "Example of Some Object Oriented Languages",
          "Advantages and Disadvantages of OOP",
        ],
      },
      {
        title: "Introduction to C++ (2 hours)",
        topics: [
          "The Need of C++",
          "Features of C++",
          "C++ Versus C",
          "History of C++",
        ],
      },
      {
        title: "C++ Language Constructs (6 hours)",
        topics: [
          "C++ Program Structure",
          "Character Set and Tokens; Keywords; Identifiers; Literals; Operators and Punctuators",
          "Variable Declaration and Expression",
          "Statements",
          "Data Type",
          "Type Conversion and Promotion Rules",
          "Preprocessor Directives",
          "Namespace",
          "User Defined Constant const",
          "Input/Output Streams and Manipulators",
          "Dynamic Memory Allocation with new and delete",
          "Condition and Looping",
          "Functions; Function Syntax; Function Overloading; Inline Functions; Default Argument; Pass by Reference; Return by Reference",
          "Array, Pointer and String",
          "Structure, Union and Enumeration",
        ],
      },
      {
        title: "Objects and Classes (6 hours)",
        topics: [
          "C++ Classes",
          "Access Specifiers",
          "Objects and the Member Access",
          "Defining Member Function",
          "Constructor; Default Constructor; Parameterized Constructor; Copy Constructor",
          "Destructors",
          "Object as Function Arguments and Return Type",
          "Array of Objects",
          "Pointer to Objects and Member Access",
          "Dynamic Memory Allocation for Objects and Object Array",
          "this Pointer",
          "static Data Member and static Function",
          "Constant Member Functions and Constant Objects",
          "Friend Function and Friend Classes",
        ],
      },
      {
        title: "Operator Overloading (5 hours)",
        topics: [
          "Overloadable Operators",
          "Syntax of Operator Overloading",
          "Rules of Operator Overloading",
          "Unary Operator Overloading",
          "Binary Operator Overloading",
          "Operator Overloading with Member and Non Member Functions",
          "Data Conversion: Basic – User Defined and User Defined – User Defined",
          "Explicit Constructors",
        ],
      },
      {
        title: "Inheritance (5 hours)",
        topics: [
          "Base and Derived Class",
          "protected Access Specifier",
          "Derived Class Declaration",
          "Member Function Overriding",
          "Forms of Inheritance: single, multiple, multilevel, hierarchical, hybrid, multipath",
          "Multipath Inheritance and Virtual Base Class",
          "Constructor Invocation in Single and Multiple Inheritances",
          "Destructor in Single and Multiple Inheritances",
        ],
      },
      {
        title: "Polymorphism and Dynamic Binding (4 hours)",
        topics: [
          "Need of Virtual Function",
          "Pointer to Derived Class",
          "Definition of Virtual Functions",
          "Array of Pointers to Base Class",
          "Pure Virtual functions and Abstract Class",
          "Virtual Destructor",
          "reinterpret_cast Operator",
          "Run‐Time Type Information; dynamic_cast Operator; typeid Operator",
        ],
      },
      {
        title:
          "Stream Computation for Console and File Input /Output (5 hours)",
        topics: [
          "Stream Class Hierarchy for Console Input /Output",
          "Testing Stream Errors",
          "Unformatted Input /Output",
          "Formatted Input /Output with ios Member functions and Flags",
          "Formatting with Manipulators",
          "Stream Operator Overloading",
          "File Input/output with Streams",
          "File Stream Class Hierarchy",
          "Opening and Closing files",
          "Read/Write from File",
          "File Access Pointers and their Manipulators",
          "Sequential and Random Access to File",
          "Testing Errors during File Operations",
        ],
      },
      {
        title: "Templates (5 hours)",
        topics: [
          "Function Template",
          "Overloading Function Template; Overloading with Functions; Overloading with other Template",
          "Class Template; Function Definition of Class Template; Non‐Template Type Arguments; Default Arguments with Class Template; Derived Class Template; Introduction to Standard Template Library; Containers; Algorithms; Iterators",
        ],
      },
      {
        title: "Exception Handling (4 hours)",
        topics: [
          "Error Handling",
          "Exception Handling Constructs (try, catch, throw)",
          "Advantage over Conventional Error Handling",
          "Multiple Exception Handling",
          "Rethrowing Exception",
          "Catching All Exceptions",
          "Exception with Arguments",
          "Exceptions Specification for Function",
          "Handling Uncaught and Unexpected Exceptions",
        ],
      },
    ],
  },
  {
    id: "computer-third-electriccircuittheory",
    title: "Electric Circuit Theory",
    objective: "",
    chapters: [
      {
        title: "Network Analysis of AC circuit & dependent sources ",
        topics: [
          "Mesh Analysis",
          "Nodal Analysis",
          "Series & parallel resonance in RLC circuits; Impedance and phase angle of series Resonant Circuit; Voltage and current in series resonant circuit; Band width of the RLC circuit; High‐Q and Low‐Q circuits",
        ],
      },
      {
        title: "Initial Conditions",
        topics: [
          "Characteristics of various network elements",
          "Initial value of derivatives",
          "Procedure for evaluating initial conditions",
          "Initial condition in the case of R‐L‐C network",
        ],
      },
      {
        title: "Transient analysis in RLC circuit by direct solution ",
        topics: [
          "Introduction",
          "First order differential equation",
          "Higher order homogeneous and non‐homogeneous differential equations",
          "Particular integral by method of undetermined coefficients",
          "Response of R‐L circuit with;DC excitation; Exponential excitation; Sinusoidal excitation",
          "Response of R‐C circuit with; DC excitation; Exponential excitation; Sinusoidal excitation Response of series R‐L‐C circuit with",
          "DC excitation",
          "Exponential excitation",
          "Sinusoidal excitation",
        ],
      },
      {
        title: "Transient analysis in RLC circuit by Laplace Transform) ",
        topics: [
          "Introduction",
          "The Laplace Transformation",
          "Important properties of Laplace transformation",
          "Use of Partial Fraction expansion in analysis using Laplace Transformations",
          "Heaviside’s partial fraction expansion theorem",
          "Response of R‐L circuit with; DC excitation; Exponential excitation; Sinusoidal excitation",
          "Response of R‐C circuit with; Exponential excitation; Sinusoidal excitation",
          "Response of parallel R‐L‐C circuit with exponential excitation",
          "Transfer functions Poles and Zeros of Networks",
        ],
      },
      {
        title: "Frequency Response of Network ",
        topics: [
          "Introduction",
          "Magnitude and phase response",
          "Bode diagrams",
          "Band width of Series & parallelResonance circuits",
          "Basic concept of filters, high pass, low pass, band pass and band stop filters",
        ],
      },
      {
        title: "Fourier Series and transform",
        topics: [
          "Basic concept of Fourier series and analysis",
          "Evaluation of Fourier coefficients for periodic non‐sinusoidal waveforms in electric networks",
          "Introduction of Fourier transforms",
        ],
      },
      {
        title: "Two‐port Parameter of Networks",
        topics: [
          "Definition of two‐port networks",
          "Short circuit admittance parameters",
          "Open circuits impedance parameters",
          "Transmission Short circuit admittance parameters",
          "Hybrid parameters",
          "Relationship and transformations between sets of parameters",
          "Application to filters",
          "Applications to transmission lines",
          "Interconnection of two‐port network (Cascade, series, parallel)",
        ],
      },
    ],
  },
  {
    id: "computer-third-theoryofcomputation",
    title: "Theory of Computation",
    objective: "",
    chapters: [
      {
        title: "Introduction (4 hours)",
        topics: [
          "Set, relation, function, Proof techniques",
          "Alphabets, language, regular expression",
        ],
      },
      {
        title: "Finite Automata (12 hours)",
        topics: [
          "Deterministic Finite Automata",
          "Non‐Deterministic Finite Automata",
          "Equivalence of regular language and finite automata",
          "Regular language, properties of regular language",
          "Pumping lemma for regular language",
          "Decision algorithms for regular languages",
        ],
      },
      {
        title: "Context free language (12 hours)",
        topics: [
          "Context free grammar",
          "Derivative trees, simplification of context free grammar",
          "Chomsky normal form",
          "Push down automata",
          "Equivalence of context free language and push down automata",
          "Pumping lemma for context free language",
          "Properties of context free language",
          "Decision algorithms for context free language",
        ],
      },
      {
        title: "Turing machine (10 hours)",
        topics: [
          "Definition of Turing machine, notation for Turing machine",
          "Computing with Turing machine",
          "Extensions of Turing machine",
          "Unrestricted grammar.",
          "Recursive function theory",
        ],
      },
      {
        title: "Undecidability (5 hours)",
        topics: [
          "The Church‐Turing thesis",
          "Halting Problem, Universal Turing machine",
          "Undecidable problems about Turing machines, grammars",
          "Properties of Recursive, Recursively enumerable languages.",
        ],
      },
      {
        title: "Computational Complexity (2 hours)",
        topics: ["Class P, Class NP, NP‐complete problems."],
      },
    ],
  },
  {
    id: "computer-third-electromagnetics",
    title: "Electromagnetics",
    objective: "",
    chapters: [
      {
        title: "Introduction (3 hours)",
        topics: [
          "Co‐ordinate system",
          "Scalar and vector fields",
          "Operations on scalar and vector fields.",
        ],
      },
      {
        title: "Electric field (11 hours)",
        topics: [
          "Coulomb’s law",
          "Electric field intensity",
          "Electric flux density",
          "Gauss’s law and applications",
          "Physical significance of divergence, Divergence theorem",
          "Electric potential, potential gradient",
          "Energy density in electrostatic field",
          "Electric properties of material medium",
          "Free and bound charges, polarization, relative permittivity, electric dipole",
          "Electric Boundary conditions",
          "Current, current density, conservation of charge, continuity equation, relaxation time",
          "Boundary value problems, Laplace and Poisson equations and their solutions, uniqueness theorem",
          "Graphical field plotting, numerical integration",
        ],
      },
      {
        title: "Magnetic field (9 hours)",
        topics: [
          "Biot‐Savart’s law",
          "Magnetic field intensity",
          "Ampere’s circuital law and its application",
          "Magnetic flux density",
          "Physical significance of curl, Stoke’s theorem",
          "Scalar and magnetic vector potential",
          "Magnetic properties of material medium",
          "Magnetic force, magnetic torque, magnetic moment, magnetic dipole, magnetization",
          "Magnetic boundary condition",
        ],
      },
      {
        title: "Wave equation and wave propagation (12 hours)",
        topics: [
          "Faraday’s law, transformer emf, motional emf.",
          "Displacement current",
          "Maxwell’s equations in integral and point forms",
          "Wave propagation in lossless and lossy dielectric",
          "Plane waves in free space, lossless dielectric, good conductor",
          "Power and pointing vector",
          "Reflection of plane wave at normal and oblique incidence",
        ],
      },
      {
        title: "Transmission lines (5 hours)",
        topics: [
          "Transmission line equations",
          "Input impedance, reflection coefficient, standing wave ratio",
          "Impedance matching, quarter wave transformer, single stub matching, double stub matching.",
        ],
      },
      {
        title: "Wave guides (4 hours)",
        topics: [
          "Rectangular wave guide",
          "Transverse electric mode, transverse magnetic mode",
        ],
      },
      {
        title: "Antennas (1 hour)",
        topics: ["Introduction to antenna, antenna types and properties."],
      },
    ],
  },
  {
    id: "computer-third-digitallogic",
    title: "Digital Logic",
    objective: "",
    chapters: [
      {
        title: "1. Introduction (3 hours)",
        topics: [
          "1.1. Definitions for Digital Signals",
          "1.2. Digital Waveforms",
          "1.3. Digital Logic",
          "1.4. Moving and Storing Digital Information",
          "1.5. Digital Operations",
          "1.6. Digital Computer",
          "1.7. Digital Integrated Circuits",
          "1.8. Digital IC Signal Levels",
          "1.9. Clock wave form",
          "1.10. Coding",
          "1.10.1. ASCII Code",
          "1.10.2. BCD",
          "1.10.3. The Excess – 3 Code",
          "1.10.4. The Gray Code",
        ],
      },
      {
        title: "2. Digital Logic (1 hours)",
        topics: [
          "2.1. The Basic Gates – NOT, OR, AND",
          "2.2. Universal Logic Gates – NOR, NAND",
          "2.3. AND‐OR‐INVERT Gates",
          "2.4. Positive and Negative Logic",
          "2.5. Introduction to HDL",
        ],
      },
      {
        title: "3. Combinational Logic Circuits (5 hours)",
        topics: [
          "3.1. Boolean Laws and Theorems",
          "3.2. Sum‐of‐Products Method",
          "3.3. Truth Table to Karnaugh Map",
          "3.4. Pairs, Quads, and Octets",
          "3.5. Karnaugh Simplifications",
          "3.6. Don’t Care Conditions",
          "3.7. Product‐of‐Sums Method",
          "3.8. Product‐of‐Sums Simplification",
          "3.9. Hazards and Hazard Covers",
          "3.10. HDL Implementation Models",
        ],
      },
      {
        title: "4. Data Processing Circuits (5 hours)",
        topics: [
          "4.1. Multiplexetures",
          "4.2. Demultiplexetures",
          "4.3. Decoder",
          "4.4. BCD‐to‐Decimal Decoders",
          "4.5. Seven‐Segment Decoders",
          "4.6. Encoder",
          "4.7. Exclusive‐OR Gates",
          "4.8. Parity Generators and Checkers",
          "4.9. Magnitude Comparator",
          "4.10. Read‐Only Memory",
          "4.11. Programmable Array Logic",
          "4.12. Programmable Logic Arrays",
          "4.13. Troubleshooting with a Logic Probe",
          "4.14. HDL Implementation of Data Processing Circuits",
        ],
      },
      {
        title: "5. Arithmetic Circuits (5 hours)",
        topics: [
          "5.1. Binary Addition",
          "5.2. Binary Subtraction",
          "5.3. Unsigned Binary Numbers",
          "5.4. Sign‐Magnitude Numbers",
          "5.5. 2’s Complement Representation",
          "5.6. 2’s Complement Arithmetic",
          "5.7. Arithmetic Building Blocks",
          "5.8. The Adder‐Subtracter",
          "5.9. Fast Adder",
          "5.10. Arithmetic Logic Unit",
          "5.11. Binary Multiplication and Division",
          "5.12. Arithmetic Circuits Using HDL",
        ],
      },
      {
        title: "\n6. Flip Flops (5 hours)",
        topics: [
          "6.1. RS Flip‐Flops",
          "6.2. Gated Flip‐Flops",
          "6.3. Edge‐Triggered RS Flip‐Flops",
          "6.4. Egde Triggered D Flip‐Flops",
          "6.5. Egde Triggered J K Flip‐Flops",
          "6.6. Flip‐Flop Timing",
          "6.7. J K Mater‐ Slave Flip‐Flops",
          "6.8. Switch Contacts Bounds Circuits",
          "6.9. Varius Representation of Flip‐Flops",
          "6.10. Analysis of Sequencial Circuits",
        ],
      },
      {
        title: "7. Registers (2 hours)",
        topics: [
          "7.1. Types of Registers",
          "7.2. Serial In – Serial Out",
          "7.3. Serial In – Parallel Out",
          "7.4. Parallel In – Serial Out",
          "7.5. Parallel In – Parallel Out",
          "7.6. Applications of Shift Registers",
        ],
      },
      {
        title: "8. Counters (5 hours)",
        topics: [
          "8.1. Asynchronous Counters",
          "8.2. Decoding Gates",
          "8.3. Synchronous Counters",
          "8.4. Changing the Counter Modulus",
          "8.5. Decade Counters",
          "8.6. Presettable Counters",
          "8.7. Counter Design as a Synthesis Problem",
          "8.8. A Digital Clock",
        ],
      },
      {
        title: "9. Sequential Machines (8 hours)",
        topics: [
          "9.1. Synchronous machines",
          "9.1.1. Clock driven models and state diagrams",
          "9.1.2. Transition tables, Redundant states",
          "9.1.3. Binary assignment",
          "9.1.4. Use of flip‐flops in realizing the models",
          "9.2. Asynchronous machines",
          "9.2.1. Hazards in asynchronous system and use of redundant",
          "branch",
          "9.2.2. Allowable transitions",
          "9.2.3. Flow tables and merger diagrams",
          "9.2.4. Excitation maps and realization of the models",
        ],
      },
      {
        title: "10. Digital Integrate Circuits (4 hours)",
        topics: [
          "10.1. Switching Circuits",
          "10.2. 7400 TTL",
          "10.3. TTL parameters",
          "10.4. TTL Overvew",
          "10.5. Open Collecter Gates",
          "10.6. Three‐state TTL Devices",
          "10.7. External Drive for TTL Lods",
          "10.8. TTL Driving External Loads",
          "10.9. 74C00 CMOS",
          "10.10. CMOS Characteristics",
          "10.11. TTL‐ to –CMOS Interface",
          "10.12. CMOS‐ to‐ TTL Interface",
        ],
      },
      {
        title: "11. Applications (2 hours)",
        topics: [
          "11.1. Multiplexing Displays",
          "11.2. Frequency Counters",
          "11.3. Time Measurement",
        ],
      },
    ],
  },
  {
    id: "computer-third-electronicdevicesandcircuits",
    title: "Electronic Devices and Circuits",
    objective: "",
    chapters: [
      {
        title: "1. Diodes (5 hours)",
        topics: [
          "1.1 The Ideal Diode",
          "1.2 Terminal Characteristics of Junction Diodes",
          "1.3 Physical Operation of Diodes",
          "1.4 Analysis of Diode Circuits",
          "1.5 Small Signal Model and Its Application",
          "1.6 Operation in the Reverse Breakdown Region ‐ Zener Diodes",
        ],
      },
      {
        title: "2. The Bipolar Junction Transistor (10 hours)",
        topics: [
          "2.1 Operation of the npn transistor in the Active Mode",
          "2.2 Graphical Representation of Transistor Characteristics",
          "2.3 Analysis of Transistor Circuits at DC",
          "2.4 Transistor as an Amplifier",
          "2.5 Small Signal Equivalent Circuit Models",
          "2.6 Graphical Load Line Analysis",
          "2.7 Biasing BJT for Discrete‐Circuit Design",
          "2.8 Basic Single‐Stage BJT Amplifier Configurations (C‐B, C‐E, C‐C)",
          "2.9 Transistor as a Switch – Cutoff and Saturation",
          "2.10 A General Large‐Signal Model for the BJT: The Ebers‐Moll Model",
        ],
      },
      {
        title: "3. Field‐Effect Transistor (9 hours)",
        topics: [
          "3.1 Structure and Physical Operation of Enhancement‐Type MOSFET",
          "3.2 Current‐Voltage Characteristics of Enhancement‐Type MOSFET",
          "3.3 The Depletion‐Type MOSFET",
          "3.4 MOSFET Circuits at DC",
          "3.5 MOSFET as an Amplifier",
          "3.6 Biasing in MOS Amplifier Circuits",
          "3.7 Junction Field‐Effect Transistor",
        ],
      },
      {
        title: "4. Output Stages and Power Amplifiers (9 hours)",
        topics: [
          "4.1 Classification of Output Stages",
          "4.2 Class A Output Stage",
          "4.3 Class B Output Stage",
          "4.4 Class AB Output Stage",
          "4.5 Biasing the Class AB Stage",
          "4.6 Power BJTs",
          "4.7 Transformer‐Coupled Push‐Pull Stages *",
          "4.8 Tuned Amplifiers",
        ],
      },
      {
        title: "5. Signal Generator and Waveform‐Shaping Circuits (6 hours)",
        topics: [
          "5.1 Basic Principles of Sinusoidal Oscillator",
          "5.2 Op Amp‐RC Oscillator Circuits",
          "5.3 LC and Crystal Oscillators",
          "5.4 Generation of Square and Triangular Waveforms Using Astable",
          "Multivibrators",
          "5.5 Integrated Circuit Timers",
          "5.6 Precision Rectifier Circuits",
        ],
      },
      {
        title:
          "6. Power Supplies, Breakdown Diodes, and Voltage Regulators* (6 hours)",
        topics: [
          "6.1 Unregulated Power Supply",
          "6.2 Bandgap Voltage Reference, a Constant Current Diodes",
          "6.3 Transistor Series Regulators",
          "6.4 Improving Regulator Performance",
          "6.5 Current Limiting",
          "6.6 Integrated Circuit Voltage Regulator",
        ],
      },
    ],
  },
];

export default ksThirdSemComputer;
