const ksFourthSemComputer = [
  {
    id: "computer-fourth-appliedmathematics",
    title: "Applied Mathematics",
    objective: "",
    chapters: [
      {
        title: "1. Complex Analysis (18 hours)",
        topics: [
          "1.1 Complex Analytic Functions",
          "1.1.1 Functions and sets in the complex plane",
          "1.1.2 Limits and Derivatives of complex functions",
          "1.1.3 Analytic functions. The Cauchy –Riemann equations",
          "1.1.4 Harmonic functions and it’s conjugate",
          "1.2 Conformal Mapping",
          "1.2.1 Mapping",
          "1.2.2 Some familiar functions as mappings",
          "1.2.3 Conformal mappings and special linear functional",
          "transformations",
          "1.2.4 Constructing conformal mappings between given domains",
          "1.3 Integral in the Complex Plane",
          "1.3.1 Line integrals in the complex plane",
          "1.3.2 Basic Problems of the complex line integrals",
          "1.3.3 Cauchy’s integral theorem",
          "1.3.4 Cauchy’s integral formula",
          "1.3.5 Supplementary problems",
          "1.4 Complex Power Series, Complex Taylor series and Lauren series",
          "1.4.1 Complex power series",
          "1.4.2 Functions represented by power series",
          "1.4.3 Taylor series, Taylor series of elementary functions",
          "1.4.4 Practical methods for obtaining power series, Laurent series",
          "1.4.5 Analyticity at infinity, zeros, singularities, residues, Cauchy’s",
          "residue theorem",
          "1.4.6 Evaluation of real integrals",
        ],
      },
      {
        title: "2. The Z‐Transform (9 hours)",
        topics: [
          "2.1 Introduction",
          "2.2 Properties of Z‐Transform",
          "2.3 Z‐ transform of elementary functions",
          "2.4 Linearity properties",
          "2.5 First shifting theorem, second shifting theorem, Initial value theorem,",
          "2.6 Final value theorem, Convolution theorem",
          "2.7 Some standard Z‐ transform",
          "2.8 Inverse Z‐Transform",
          "2.9 Method for finding Inverse Z‐Transform",
          "2.10 Application of Z‐Transform to difference equations",
        ],
      },
      {
        title: "3. Partial Differential Equations (12 hours)",
        topics: [
          "3.1 Linear partial differential equation of second order, their classification and solution",
          "3.2 Solution of one dimensional wave equation, one dimensional heat equation, two dimensional heat equation and Laplace equation (Cartesian and polar form) by variable separation method",
        ],
      },
      {
        title: "4. Fourier Transform (6 hours)",
        topics: [
          "4.1 Fourier integral theorem, Fourier sine and cosine integral; complex",
          "form of Fourier integral",
          "4.2 Fourier transform, Fourier sine transform, Fourier cosine",
          "transform and their properties",
          "4.3 Convolution, Parseval’s identity for Fourier transforms",
          "4.4 Relation between Fourier transform and Laplace transform",
        ],
      },
    ],
  },
  {
    id: "computer-fourth-datastructureandalgorithmn",
    title: "Data Structure and Algorithmn",
    objective: "",
    chapters: [
      {
        title: "Concept of data structure (2 hours)",
        topics: [
          "Introduction: data types, data structures and abstract data types",
          "Introduction to algorithms",
        ],
      },
      {
        title: "The Stack and Queue (6 hours)",
        topics: [
          "Stack operation",
          "Stack application: Evaluation of Infix, Postfix and Prefix expressions",
          "Operations in queue, Enqueue and Dequeue",
          "Linear and circular queue",
          "Priority queue",
        ],
      },
      {
        title: "List ( 3 hours )",
        topics: [
          "Definition; Static and dynamic list structure; Array implementation of lists; Queues as list",
        ],
      },
      {
        title: "Linked lists ( 5 hours )",
        topics: [
          "Dynamic implementation",
          "Operations in linked list",
          "Linked stacks and queues",
          "Doubly linked lists and its applications",
        ],
      },
      {
        title: "Recursion ( 4 hours )",
        topics: [
          "Principle of recursion",
          "TOH and Fibonacci sequence",
          "Applications of recursion",
        ],
      },
      {
        title: "Trees ( 7 hours )",
        topics: [
          "Concept",
          "Operation in Binary tree",
          "Tree search, insertion/deletions",
          "Tree traversals (pre‐order, post‐order and in‐order)",
          "Height, level and depth of a tree",
          "AVL balanced trees and Balancing algorithm",
          "The Huffman algorithm",
          "B‐Tree",
          "Red Black Tree",
        ],
      },
      {
        title: "Sorting ( 5 hours )",
        topics: [
          "Types of sorting: internal and external",
          "Insertion and selection sort",
          "Exchange sort",
          "Merge and Redix sort",
          "Shell sort",
          "Heap sort as a priority queue",
          "Big ‘O’ notation and Efficiency of sorting",
        ],
      },
      {
        title: "Searching ( 5 hours )",
        topics: [
          "Search technique",
          "Sequential, Binary and Tree search",
          "General search tree",
          "Hashing; Hash function and hash tables; Collision resolution technique",
        ],
      },
      {
        title: "Growth Functions ( 2 hours)",
        topics: [
          "Asymptotic notations: θ , O, Ω , o,ω notations and their properties",
        ],
      },
      {
        title: "Graphs ( 6 hours )",
        topics: [
          "Representation and applications",
          "Transitive closure",
          "Warshall’s algorithm",
          "Graphs type",
          "Graph traversal and Spanning forests; Depth First Traversal and Breadth First Traversal; Topological sorting: Depth first, Breadth first topological sorting; Minimum spanning trees, Prim’s, Kruskal’s and Round‐ Robin algorithms",
          "Shortest‐path algorithm; Greedy algorithm; Dijkstra’s Algorithm",
        ],
      },
    ],
  },
  {
    id: "computer-fourth-discretestructure",
    title: "Discrete Structure",
    objective: "",
    chapters: [
      {
        title: "Logic, Induction and Reasoning (12 hours)",
        topics: [
          "Proposition and Truth function",
          "Propositional Logic",
          "Expressing statements in Logic Propositional Logic",
          "The predicate Logic",
          "Validity",
          "Informal Deduction in Predicate Logic",
          "Rules of Inference and Proofs",
          "Informal Proofs and Formal Proofs",
          "Elementary Induction and Complete Induction",
          "Methods of Tableaux",
          "Consistency and Completeness of the System",
        ],
      },
      {
        title: "inite State Automata (10 hours)",
        topics: [
          "Sequential Circuits and Finite state Machine",
          "Finite State Automata",
          "Language and Grammars",
          "Non‐deterministic Finite State Automata",
          "Language and Automata",
          "Regular Expression and its characteristics",
        ],
      },
      {
        title: "ecurrence Relation (8 hours)",
        topics: [
          "Recursive Definition of Sequences",
          "Solution of Linear recurrence relations",
          "Solution to Nonlinear Recurrence Relations",
          "Application to Algorithm Analysis",
        ],
      },
      {
        title: "raph Theory (15 hours)",
        topics: [
          "Undirected and Directed Graphs",
          "Walk Paths, Circuits, Components",
          "Connectedness Algorithm",
          "Shortest Path Algorithm",
          "Bipartite Graphs, Planar Graphs, Regular Graphs",
          "Planarity Testing Algorithms",
          "Eulerian Graph",
          "Hamiltonian Graph",
          "Tree as a Directed Graph",
          "Binary Tree, Spanning Tree",
          "Cut sets and Cut vertices",
          "Network Flows, Maxflow and Mincut Theorem",
          "Data Structures Representing Trees and Graphs in Computer",
          "Network Application of Trees and Graphs",
          "Concept of Graph Coloring",
        ],
      },
    ],
  },
  {
    id: "computer-fourth-electricmachine",
    title: "Electric Machine",
    objective: "",
    chapters: [
      {
        title: "1. Magnetic Circuits and Induction (4hours)",
        topics: [
          "1.1 Magnetic Circuits",
          "1.2 Ohm’s Law for Magnetic Circuits",
          "1.3 Series and Parallel magnetic circuits",
          "1.4 Core with air gap",
          "1.5 B‐H relationship (Magnetization Characteristics)",
          "1.6 Hysteresis with DC and AC excitation",
          "1.7 Hysteresis Loss and Eddy Current Loss",
          "1.8 Faraday’s Law of Electromagnetic Induction, Statically and Dynamically Induced EMF",
          "1.9 Force on Current Carrying Conductor",
        ],
      },
      {
        title: "2. Transformer (8 hours)",
        topics: [
          "2.1 Constructional Details, recent trends",
          "2.2 Working principle and EMF equation",
          "2.3 Ideal Transformer",
          "2.4 No load and load Operation",
          "2.5 Operation of Transformer with load",
          "2.6 Equivalent Circuits and Phasor Diagram",
          "2.7 Tests: Polarity Test, Open Circuit test, Short Circuit test and Equivalent Circuit Parameters",
          "2.8 Voltage Regulation",
          "2.9 Losses in a transformer",
          "2.10 Efficiency, condition for maximum efficiency and all day efficiency",
          "2.11 Instrument Transformers: Potential Transformer (PT) and Current Transformer (CT)",
          "2.12 Auto transformer: construction, working principle and Cu saving",
          "2.13 Three phase Transformers",
        ],
      },
      {
        title: "3. DC Generator (6 hours)",
        topics: [
          "3.1 Constructional Details and Armature Winding",
          "3.2 Working principle and Commutator Action",
          "3.3 EMF equation",
          "3.4 Method of excitation: separately and self excited, Types of DC Generator",
          "3.5 Characteristics of series, shunt and compound generator",
          "3.6 Losses in DC generators",
          "3.7 Efficiency and Voltage Regulation",
        ],
      },
      {
        title: "4. DC Motor (6 hours)",
        topics: [
          "4.1 Working principle and Torque equation",
          "4.2 Back EMF",
          "4.3 Method of excitation, Types of DC motor",
          "4.4 Performance Characteristics of D.C. motors",
          "4.5 Starting of D.C. Motors: 3 point and 4 point starters",
          "4,6 Speed control of D.C. motors: Field Control, Armature Control",
          "4.7 Losses and Efficiency",
        ],
      },
      {
        title: "5. Three Phase Induction Machines (6 hours)",
        topics: [
          "5.1 Three Phase Induction Motor",
          "5.1.1 Constructional Details and Types",
          "5.1.2 Operating Principle, Rotating Magnetic Field, Synchronous Speed, Slip, Induced EMF, Rotor Current and its frequency, Torque Equation",
          "5.1.3 Torque‐Slip characteristics",
          "5.2 Three Phase Induction Generator",
          "5.2.1 Working Principle, voltage build up in an Induction Generator",
          "5.2.2 Power Stages",
        ],
      },
      {
        title: "6. Three Phase Synchronous Machines (6 hours)",
        topics: [
          "6.1 Three Phase Synchronous Generator",
          "6.1.1 Constructional Details, Armature Windings, Types of Rotor, Exciter",
          "6.1.2 Working Principle",
          "6.1.3 EMF equation, distribution factor, pitch factor",
          "6.1.4 Armature Reaction and its effects",
          "6.1.5 Alternator with load and its phasor diagram",
          "6.2 Three Phase Synchronous Motor",
          "6.2.1 Principle of operation",
          "6.2.2 Starting methods",
          "6.2.3 No load and Load operation, Phasor Diagram",
          "6.2.4 Effect of Excitation and power factor control",
        ],
      },
      {
        title: "7. Fractional Kilowatt Motors (6 hours)",
        topics: [
          "2.14 Single phase Induction Motors: Construction and Characteristics",
          "2.15 Double Field Revolving Theory",
          "2.16 Split phase Induction Motor",
          "7.1.1 Capacitors start and run motor",
          "7.1.2 Reluctance start motor",
          "2.17 Alternating Current Series motor and Universal motor",
          "2.18 Special Purpose Machines: Stepper motor, Schrage motor and Servo motor",
        ],
      },
    ],
  },
  {
    id: "computer-fourth-instrumentationi",
    title: "Instrumentation I",
    objective: "",
    chapters: [
      {
        title: "1. Instrumentations Systems (2 hours)",
        topics: [
          "1.1 Functions of components of instrumentation system introduction, signal processing , Signal transmission ,output indication",
          "1.2 Need for electrical, electronics, pneumatic and hydraulic working media systems and conversion devices",
          "1.3 Analog and digital systems",
        ],
      },
      {
        title: "2. Theory of measurement (10 hours)",
        topics: [
          "2.1 Static performance parameters ‐ accuracy, precision, sensitivity, resolution and linearity",
          "2.2 Dynamic performance parameters ‐ response time, frequency response and bandwidth",
          "2.3 Error in measurement",
          "2.4 Statistical analysis of error in measurement",
          "2.5 Measurement of voltage & current (moving coil & moving iron instruments)",
          "2.6 Measurement of low, high & medium resistances",
          "2.7 AC bridge & measurement of inductance and capacitance",
        ],
      },
      {
        title: "3. Transducer (8 hours)",
        topics: [
          "3.1 Introduction",
          "3.2 Classification",
          "3.3 Application",
          "3.3.1 Measurement of mechanical variables, displacement, strain. velocity. acceleration and vibration",
          "3.3.2 Measurement of process variables ‐ temperature pressure, level, fluid flow, chemical constituents in gases or liquids, pH and humidity.",
          "3.3.3 Measurement of bio‐physical variables blood pressure and",
          "myoelectric potentials",
        ],
      },
      {
        title: "4. Electrical Signal Processing and transmission (6 hours)",
        topics: [
          "4.1 Basic Op‐amp characteristics",
          "4.2 Instrumentation amplifier",
          "4.3 Signal amplification, attenuation, integration, differentiation, network isolation, wave shaping",
          "4.4 Effect of noise, analog filtering, digital filtering",
          "4.5 Optical communication, fibre optics, electro‐optic conversion devices",
        ],
      },
      {
        title: "5. Analog ‐ Digital and Digital ‐ Analog Conversion (6 hours)",
        topics: [
          "5.1 Analog signal and digital signal",
          "5.2 Digital to analog convertors ‐ weighted resistor type, R‐2R ladder type, DAC Errors",
          "5.3 Analog to digital convertors ‐ successive approximation type, ramp type, dual ramp type, flash type, ADC errors",
        ],
      },
      {
        title: "6. Digital Instrumentation (5 hours)",
        topics: [
          "6.1 Sample data system, sample and hold circuit",
          "6.2 Components of data acquisition system",
          "6.3 Interfacing to the computer",
        ],
      },
      {
        title: "7. Electrical equipment (8 hours)",
        topics: [
          "7.1 Wattmeter",
          "7.1.1 Types",
          "7.1.2 Working principles",
          "7.2 Energy meter",
          "7.2.1 Types",
          "7.2.2 Working principles",
          "7.3 Frequency meter",
          "7.3.1 Types",
          "7.3.2 Working principles",
          "7.4 Power factor meter",
          "7.5 Instrument transformers",
        ],
      },
    ],
  },
  {
    id: "computer-fourth-microprocessor",
    title: "Microprocessor",
    objective: "",
    chapters: [
      {
        title: "Introduction (4 hours)",
        topics: [
          "Introduction and History of Microprocessors",
          "Basic Block Diagram of a Computer",
          "Organization of Microprocessor Based System",
          "Bus Organization",
          "Stored program Concept and Von Neumann Machine",
          "Processing Cycle of a Stored Program Computer",
          "Microinstructions and Hardwired/Microprogrammed Control Unit",
          "Introduction to Register Transfer Language",
        ],
      },
      {
        title: "Programming with 8085 Microprocessor (10 hours)",
        topics: [
          "Internal Architecture and Features of 8085 microprocessor",
          "Instruction Format and Data Format",
          "Addressing Modes of 8085",
          "Intel 8085 Instruction Set",
          "Various Programs in 8085",
          "Simple Programs with Arithmetic and Logical Operations",
          "Conditions and Loops",
          "Array and Table Processing",
          "Decimal BCD Conversion",
          "Multiplication and Division",
        ],
      },
      {
        title: "Programming with 8086 Microprocessor (12 hours)",
        topics: [
          "Internal Architecture and Features of 8086 Microprocessor; BIU and Components; EU and Components; EU and BIU Operations; Segment and Offset Address",
          "Addressing Modes of 8086",
          "Assembly Language Programming",
          "High Level versus Low Level Programming",
          "Assembly Language Syntax; Comments; Reserved words; Identifiers; Statements; Directives; Operators; Instructions",
          "EXE and COM programs",
          "Assembling, Linking and Executing",
          "One Pass and Two Pass Assemblers",
          "Keyboard and Video Services",
          "Various Programs in 8086; Simple Programs for Arithmetic, Logical, String Input/Output; Conditions and Loops; Array and String Processing; Read and Display ASCII and Decimal Numbers; Displaying Numbers in Binary and Hexadecimal Formats",
        ],
      },
      {
        title: "Microprocessor System (10 hours)",
        topics: [
          "Pin Configuration of 8085 and 8086 Microprocessors",
          "Bus Structure; Synchronous Bus; Asynchronous Bus; Read and Write Bus Timing of 8085 and 8086 Microprocessors",
          "Memory Device Classification and Hierarchy",
          "Interfacing I/O and Memory; Address Decoding; Unique and Non Unique Address Decoding; I/O Mapped I/O and Memory Mapped I/O; Serial and Parallel Interfaces; I/O Address Decoding with NAND and Block Decoders (8085, 8086); Memory Address Decoding with NAND, Block and PROM Decoders (8085, 8086)",
          "Parallel Interface; Modes: Simple, Wait, Single Handshaking and Double Handshaking; Introduction to Programmable Peripheral Interface (PPI)",
          "Serial Interface; Synchronous and Asynchronous Transmission; Serial Interface Standards: RS232, RS423, RS422, USB; Introduction to USART",
          "Introduction to Direct Memory Access (DMA) and DMA Controllers",
        ],
      },
      {
        title: "Interrupt Operations (5 hours)",
        topics: [
          "Polling versus Interrupt",
          "Interrupt Processing Sequence",
          "Interrupt Service Routine",
          "Interrupt Processing in 8085; Interrupt Pins and Priorities; Using Programmable Interrupt Controllers (PIC); Interrupt Instructions",
          "Interrupt Processing in 8086; Interrupt Pins; Interrupt Vector Table and its Organization; Software and Hardware Interrupts; Interrupt Priorities",
          "Advanced Topics (4 hours); Multiprocessing Systems; Real and Pseudo‐Parallelism; Flynn’s Classification; Instruction Level, Thread Level and Process Level Parallelism; Interprocess Communication, Resource Allocation and Deadlock; Features of Typical Operating System; Different Microprocessor Architectures; Register Based and Accumulator Based Architecture; RISC and CISC Architectures; Digital Signal Processors",
        ],
      },
      {
        title: "Advanced Topics (4 hours)",
        topics: [
          "Multiprocessing Systems; Real and Pseudo‐Parallelism; Flynn’s Classification; Instruction Level, Thread Level and Process Level Parallelism; Interprocess Communication, Resource Allocation and Deadlock; Features of Typical Operating System",
          "Different Microprocessor Architectures; Register Based and Accumulator Based Architecture; RISC and CISC Architectures; Digital Signal Processors",
        ],
      },
    ],
  },
  {
    id: "computer-fourth-numericalmethods",
    title: "Numerical Methods",
    objective: "",
    chapters: [
      {
        title:
          "1. Introduction, Approximation and errors of computation (4 hours)",
        topics: [
          "1.1. Introduction, Importance of Numerical Methods",
          "1.2. Approximation and Errors in computation",
          "1.3. Taylor’s series",
          "1.4. Newton’s Finite differences (forward , Backward, central",
          "difference, divided difference)",
          "1.5. Difference operators, shift operators, differential operators",
          "1.6. Uses and Importance of Computer programming in Numerical",
          "Methods.",
        ],
      },
      {
        title: "2. Solutions of Nonlinear Equations (5 hours)",
        topics: [
          "2.1. Bisection Method",
          "2.2. Newton Raphson method ( two equation solution)",
          "2.3. Regula‐Falsi Method , Secant method",
          "2.4. Fixed point iteration method",
          "2.5. Rate of convergence and comparisons of these Methods",
        ],
      },
      {
        title: "3. Solution of system of linear algebraic equations (8 hours)",
        topics: [
          "3.1. Gauss elimination method with pivoting strategies",
          "3.2. Gauss‐Jordan method",
          "3.3. LU Factorization",
          "3.4. Iterative methods (Jacobi method, Gauss‐Seidel method)",
          "3.5. Eigen value and Eigen vector using Power method",
        ],
      },
      {
        title: "4. Interpolation (8 hours)",
        topics: [
          "4.1. Newton’s Interpolation ( forward, backward)",
          "4.2. Central difference interpolation: Stirling’s Formula, Bessel’s",
          "Formula",
          "4.3. Lagrange interpolation",
          "4.4. Least square method of fitting linear and nonlinear curve for",
          "discrete data and continuous function",
          "4.5. Spline Interpolation (Cubic Spline)",
        ],
      },
      {
        title: "5. Numerical Differentiation and Integration (6 hours)",
        topics: [
          "5.1. Numerical Differentiation formulae",
          "5.2. Maxima and minima",
          "5.3. Newton‐Cote general quadrature formula",
          "5.4. Trapezoidal, Simpson’s 1/3, 3/8 rule",
          "5.5. Romberg integration",
          "5.6. Gaussian integration ( Gaussian – Legendre Formula 2 point and 3 point)",
        ],
      },
      {
        title: "6. Solution of ordinary differential equations (6 hours)",
        topics: [
          "6.1. Euler’s and modified Euler’s method",
          "6.2. Runge Kutta methods for 1st and 2nd order ordinary differential equations",
          "6.3. Solution of boundary value problem by finite difference method and shooting method.",
        ],
      },
      {
        title:
          "7. Numerical solution of Partial differential Equation (8 hours)",
        topics: [
          "7.1. Classification of partial differential equation(Elliptic, parabolic, and Hyperbolic)",
          "7.2. Solution of Laplace equation ( standard five point formula with iterative method)",
          "7.3. Solution of Poisson equation (finite difference approximation)",
          "7.4. Solution of Elliptic equation by Relaxation Method",
          "7.5. Solution of one dimensional Heat equation by Schmidt method Practical:",
        ],
      },
    ],
  },
];

export default ksFourthSemComputer;
