const modalData = {
  Aerospace: {
    First: [
      "Applied Mechanics",
      "Basic Electrical Engineering",
      "Engineering Drawing I",
      "Engineering Math I",
      "Engineering Physics",
      "Workshop Technology",
    ],
    Second: [
      "Engineering Mathematics - II",
      "Engineering Drawing- II",
      "Basic Electronics Engineering",
      "Computer Programming",
      "Engineering Chemistry",
      "Fundamentals of Thermodynamics and Heat Transfer",
    ],
    Third: [
      "Engineering Mathematics - III",
      "Fundamentals of Aerospace Engineering",
      "Engineering Mechanics ",
      "Fluid Mechanics",
      "Applied Thermodynamics and Heat Transfer",
      "Computer Aided Design and Manufacturing",
    ],
    Fourth: [
      "Probability and Statistics",
      "Control Systems",
      "Aerospace Materials",
      "Aerodynamics",
      "Strength of Materials",
      "Theory of Mechanism and Machine I",
    ],
    Fifth: [
      "Numerical Methods",
      "Aircraft Manufacturing Process ",
      "Theory of Vibration",
      "Continuum Mechanics",
      "Aircraft Propulsion",
      "Fault Monitoring and Diagnosis",
    ],
    Sixth: [
      "Avionics",
      "Aircraft Maintenance Engineering ",
      "Finite Element Method ",
      "Aircraft Environment Control System",
      "Flight Dynamics",
      "Unmanned Air Vehicle Synthesis",
    ],
    Seventh: [
      "Aircraft Preliminary Design",
      "Computational Fluid Dynamics",
      "Air Traffic Management",
      "Aircraft Structures",
      "Embedded Systems in Avionics",
      "Elective",
      "Project I",
    ],
    Eighth: [
      "Internship",
      "Aviation Professional Practices",
      "Elective II",
      "Elective III",
      "Project II",
    ],
  },
  Agricultural: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Architecture: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Automobile: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Civil: {
    First: [
      "Engineering Drawing I",
      "Engineering Mathematics I",
      "Thermodynamics and Heat Transfer",
      "Engineering Chemistry",
      "Workshop Technology",
      "Computer Programming",
    ],
    Second: [
      "Engineering Mathematics II",
      "Basic Electronics Engineering",
      "Engineering Drawing II",
      "Engineering Physics",
      "Applied Mechanics",
      "Basic Electrical Engineering",
    ],
    Third: [
      "Civil Engineering Materials",
      "Engineering Mathematics III",
      "Applied Mechanics(Dynamics)",
      "Engineering Geology I",
      "Strength of Materials",
      "Surveying I",
      "Fluid mechanics",
    ],
    Fourth: [
      "Hydraulics",
      "Surveying II",
      "Theory of Structures I",
      "Probability And Statistics",
      "Engineering Geology II",
      "Building Drawing",
      "Soil Mechanics",
    ],
    Fifth: [
      "Theory of structure II",
      "Water Supply Engineering",
      "Engineering hydrology",
      "Concrete Technology and masonry structure",
      "Numerical Methods",
      "Foundation Engineering",
      "Survey Camp",
    ],
    Sixth: [
      "Design of Steel and Timber Structure",
      "Communication English",
      "Engineering Economics",
      "Building Technology",
      "Sanitary Engineering",
      "Transportation Engineering",
      "Irrigation and Drainage",
    ],
    Seventh: [
      "Hydropower Engineering",
      "Project Engineering",
      "Transportation Engineering II",
      "Estimating & Costing",
      "Design of RCC Structure",
      "Project (Part I) ",
      "Elective I : Bio-Engineering",
      "Elective I : Water and WasteWater Quality Analysis",
      "Elective I : Soil Conservation and Watershed Management",
      "Elective I : Trail Suspension Bridge",
      "Elective I : Structural Dynamics",
      "Elective I : Seismic Resistant Design of Masonry Structures",
      "Elective I : Solid Waste Management",
      "Elective I : Ropeway Engineering",
      "Elective I : Transportation Planning and Engineering",
      "Elective I : Rock Engineering",
      "Elective I : Community Development and Participatory Rural Approach",
      "Elective I : Earth Hazard",
    ],
    Eighth: [
      "Technology Environment and Society",
      "Construction Management",
      "Project (Part II)",
      "Engineering Professional Practice",
      "Computational Techniques in Civil Engineering",
      "Elective II : Climate Change",
      "Elective II : Environmental Management System",
      "Elective II : Groundwater Engineering",
      "Elective II : Seismic Risk Assessment",
      "Elective II : Water Quality Management",
      "Elective II : Traffic and Transport Modeling",
      "Elective II : Traffic Engineering and Management",
      "Elective II : Rural Road Engineering",
      "Elective II : Rock Slope Engineering",
      "Elective II : Rock Mechanics",
      "Elective II : Public Health and Risk Assessment",
      "Elective II : Vulnerability Assessment and Retrofitting Techniques",
      "Elective II : Design of Bridges",
      "Elective II : Introduction to Prestressed Concrete Analysis and Design",
      "Elective II : Post Disaster Water and Sanitation Management",
      "Elective II : Hill Irrigation Engineering",
    ],
  },
  Computer: {
    First: [
      "Applied Mechanics",
      "Basic Electrical Engineering",
      "C Programming",
      "Drawing I",
      "Engineering Physics",
      "Maths I",
    ],
    Second: [
      "Basic Electronics",
      "Engineering Chemistry",
      "Drawing II",
      "Math II",
      "Thermodynamics and Heat Transfer",
      "Workshop Technology",
    ],
    Third: [
      "Digital Logic",
      "Electric Circuit Theory",
      "Electromagnetics",
      "Electronic Devices and Circuits",
      "Engineering Math III",
      "Object Oriented Programming",
      "Theory of Computation",
    ],
    Fourth: [
      "Applied Mathematics",
      "Data Structure and Algorithms",
      "Discrete Structures",
      "Electrical Machines",
      "Instrumentation I",
      "Microprocessor",
      "Numerical Methods",
    ],
    Fifth: [
      "Communication English",
      "Computer Graphics",
      "Computer Organization and Architecture",
      "Data Communication",
      "Instrumentation II",
      "Probability and Statistics",
      "Software Engineering",
    ],
    Sixth: [
      "Artificial Intelligence",
      "Database Management System",
      "Embedded System",
      "Engineering Economics",
      "Minor Project",
      "Object Oriented Analysis and Design",
      "Operating System",
    ],
    Seventh: [
      "Computer Network",
      "Digital Signal Analysis and Processing",
      "Distributed System",
      "Energy, Environment and Society",
      "ICT Project Management",
      "Organization and Management",
      "Project (Part A)",
      "Elective I",
    ],
    Eighth: [
      "Engineering Professional Practice",
      "Information System",
      "Internet and Intranet",
      "Project (Part B)",
      "Simulation and Modeling",
      "Elective II",
      "Elective III",
    ],
  },
  Electrical: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Electronics: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Geomatics: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Industial: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Mechanical: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
};

export default modalData;
