const modalData = {
  Aerospace: {
    First: [
      "Applied Mechanics",
      "Basic Electrical Engineering",
      "Engineering Drawing I",
      "Engineering Math I",
      "Engineering Physics",
      "Workshop Technology",
    ],
    Second: [
      "Engineering Mathematics - II",
      "Engineering Drawing- II",
      "Basic Electronics Engineering",
      "Computer Programming",
      "Engineering Chemistry",
      "Fundamentals of Thermodynamics and Heat Transfer",
    ],
    Third: [
      "Engineering Mathematics - III",
      "Fundamentals of Aerospace Engineering",
      "Engineering Mechanics ",
      "Fluid Mechanics",
      "Applied Thermodynamics and Heat Transfer",
      "Computer Aided Design and Manufacturing",
    ],
    Fourth: [
      "Probability and Statistics",
      "Control Systems",
      "Aerospace Materials",
      "Aerodynamics",
      "Strength of Materials",
      "Theory of Mechanism and Machine I",
    ],
    Fifth: [
      "Numerical Methods",
      "Aircraft Manufacturing Process ",
      "Theory of Vibration",
      "Continuum Mechanics",
      "Aircraft Propulsion",
      "Fault Monitoring and Diagnosis",
    ],
    Sixth: [
      "Avionics",
      "Aircraft Maintenance Engineering ",
      "Finite Element Method ",
      "Aircraft Environment Control System",
      "Flight Dynamics",
      "Unmanned Air Vehicle Synthesis",
    ],
    Seventh: [
      "Aircraft Preliminary Design",
      "Computational Fluid Dynamics",
      "Air Traffic Management",
      "Aircraft Structures",
      "Embedded Systems in Avionics",
      "Elective",
      "Project I",
    ],
    Eighth: [
      "Internship",
      "Aviation Professional Practices",
      "Elective II",
      "Elective III",
      "Project II",
    ],
  },
  Agricultural: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Architecture: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Automobile: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Civil: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Computer: {
    First: [
      "Applied Mechanics",
      "Basic Electrical Engineering",
      "C Programming",
      "Drawing I",
      "Engineering Physics",
      "Maths I",
    ],
    Second: [
      "Basic Electronics",
      "Engineering Chemistry",
      "Drawing II",
      "Math II",
      "Thermodynamics and Heat Transfer",
      "Workshop Technology",
    ],
    Third: [
      "Digital Logic",
      "Electric Circuit Theory",
      "Electromagnetics",
      "Electronic Devices and Circuits",
      "Engineering Math III",
      "Object Oriented Programming",
      "Theory of Computation",
    ],
    Fourth: [
      "Applied Mathematics",
      "Data Structure and Algorithmn",
      "Discrete Structure",
      "Electric Machine",
      "Instrumentation I",
      "Microprocessor",
      "Numerical Methods",
    ],
    Fifth: [
      "Communication English",
      "Computer Graphics",
      "Computer Organization and Architecture",
      "Data Communication",
      "Instrumentation II",
      "Probability and Statistics",
      "Software Engineering",
    ],
    Sixth: [
      "Artificial Intelligence",
      "Database Management System",
      "Embedded System",
      "Engineering Economics",
      "Minor Project",
      "Object Oriented Analysis and Design",
      "Operating System",
    ],
    Seventh: [
      "Computer Network",
      "Digital Signal Analysis and Processing",
      "Distributed System",
      "Energy, Environment and Society",
      "ICT Project Management",
      "Organization and Management",
      "Project (Part A)",
      "Elective I",
    ],
    Eighth: [
      "Engineering Professional Practice",
      "Information System",
      "Internet and Intranet",
      "Project (Part B)",
      "Simulation and Modeling",
      "Elective II",
      "Elective III",
    ],
  },
  Electrical: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Electronics: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Geomatics: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Industial: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
  Mechanical: {
    First: [],
    Second: [],
    Third: [],
    Fourth: [],
    Fifth: [],
    Sixth: [],
    Seventh: [],
    Eighth: [],
  },
};

export default modalData;
